### ISSUE TITLE
LookupEditor filter using as parameter user fields connected

### ISSUE THREAD

**Issue by juliermefelix** [serenity-is/Serenity#2754]
Dear,
I need to filter the dropdownlist so that only the church appears that is registered with the user, that is, the user can only see his church.
Note: admin user can view all.
picture 1
User Registration, where it was informed which church the user belongs to.
![tela2](https://user-images.githubusercontent.com/7516443/31543959-001d94fc-afef-11e7-9106-cfc22f5d2147.JPG)

picture 2
view of the dropdownlist bringing all the churches. I would like it to show only the church based on the user.
![tela1](https://user-images.githubusercontent.com/7516443/31543986-2b3760b4-afef-11e7-87ed-bb6006647936.JPG)

code
InscritosColumns.cs
` [LookupEditor(typeof(Gerencia.Entities.IgrejaRow)), QuickFilter, Width(200)]
        public String IdIgrejaIgrejaNome { get; set; }`

admin user can view all churches, here is correct, as shown in the image below.
![tela3](https://user-images.githubusercontent.com/7516443/31544158-db2880c0-afef-11e7-80c9-0b2b54889c2e.JPG)

what should I do to display only the church in the user-based dropdownlist logged in?

**Comment by ANDY7575** [comment]
@juliermefelix  share ur row.cs code i need to check attribute u applied..
thanx in adv..
Aniket

**Comment by juliermefelix** [comment]
follows as requested
[IgrejaRepository_cs.txt](https://github.com/volkanceylan/Serenity/files/1819314/IgrejaRepository_cs.txt)
[IgrejaRow_cs.txt](https://github.com/volkanceylan/Serenity/files/1819315/IgrejaRow_cs.txt)
[IgrejaLookup_cs.txt](https://github.com/volkanceylan/Serenity/files/1819316/IgrejaLookup_cs.txt)

**Comment by ANDY7575** [comment]
@juliermefelix thank you sir..
