### ISSUE TITLE
Server-side validation with error message under property

### ISSUE THREAD

**Issue by lucky3** [serenity-is/Serenity#4625]
Hi guys.

I didn't find any example of displaying error validation message to the end user, when there is a need for complex, server-side validation, which wouldn't result in pop-up. What I am trying to achieve is to color red the offending property and display error message under it, when server side validation fails. An example of something similar would be some server side calculation, which needs data from DB. I would like to display this information under the validated property, not in pop-up.

I tried with throwing ValidationException or DataValidation and used various overloads (using Row and Field as parameters for example) and it always results in error pop-up.

Is there an example of how to do that?

**Comment by edwardch** [comment]
_I haven't tried this myself_, but you could possibly add some method to your `xyzEndpoint.cs` called `ValidateYourField`, then in your xyzDialog.ts you could do something like this

```ts
this.form.YourField.addValidationRule(this.uniqueName, e => {
	var isValid = xyzService.ValidateYourField({SomeParameter: this.form.YourField.value});

	if (!isValid) {
		return "You broke YourField's validation";
	}
});
```

My syntax of calling that service from TypeScript is probably wrong, it might need to look more like:
```ts
this.form.YourField.addValidationRule(this.uniqueName, e => {
	xyzService.ValidateYourField(
		{
			SomeParameter: this.form.YourField.value
		}, response => {
			// do something here to check if validation is ok
			return "You broke YourField's validation";
		}
	);
});
```

Try out a few things and see if it works...
