### ISSUE TITLE
datepicker localization doesn't work,because of   function  in the Serenity.CoreLib:  toLowerCase()

### ISSUE THREAD

**Issue by haoas** [serenity-is/Serenity#4718]
th function jQueryDatepickerInitialization in the Serenity.CoreLib  has a  statement   `var culture = ($('html').attr('lang') || 'en').toLowerCase();`，and we can find  "lang" is from   `<html lang="@System.Globalization.CultureInfo.CurrentUICulture.Name" class="no-js@(hideNav ? " no-navigation" : "")">`  in _Layout.cshtml. Because  the "CurrentUICulture.Name" is uppercase,so the datepicker can't find the right language resource.

**Comment by osmanaslancan** [comment]
https://github.com/serenity-is/Serenity/blob/40e8640c03370098aef7145b0d08a448f0765410/src/Serenity.Scripts/CoreLib/UI/Editors/DateEditor.ts#L420
Please check out lines below it.
