### ISSUE TITLE
Validating required FileUploadEditor

### ISSUE THREAD

**Issue by c9482** [serenity-is/Serenity#4842]
This never fires on a required field with FileUploadEditor attribute:
`            this.form.CertificateOfInsurancePath.addValidationRule(this.uniqueName, e => {
                if (this.form.CertificateOfInsurancePath.value === null) {
                    return "Please upload the certificate of insurance";
                }
            });
`
Is this by design or a bug? Many thanks in advance.

**Comment by edwardch** [comment]
Did you also try
```ts
if (!this.form.CertificateOfInsurancePath.value)
```
as your condition?

**Comment by c9482** [comment]
Yes, I did. Same result. Thanks.

**Comment by VictorTomaili** [comment]
Fixed
