### ISSUE TITLE
*low priority* Sergen 3.12.4 When specifying 'Assemblies' property in sergen.json, Serenity will not auto-detect whether to use bin/debug or bin/release on Windows

### ISSUE THREAD

**Issue by OpenlabWA** [serenity-is/Serenity#4909]
Issue: 
Assembly path has '/' replaced with the OS directory separator ( '\' in windows). Shortly after, we look for /bin/debug and /bin/release which will always return -1 breaking the check of release or debug directory.

var assemblyFile1 = Path.GetFullPath(assemblyFiles[i].Replace('/', Path.DirectorySeparatorChar));
var binDebugIdx = assemblyFile1.IndexOf("/bin/Debug/", StringComparison.OrdinalIgnoreCase);

https://github.com/volkanceylan/Serenity/blob/f9b1226dc54af26b72c8db782b10dde485704e61/Serenity.CodeGenerator/Commands/ServerTypingsCommand.cs#L93

Occurs:
When referencing assmblies in the Sergen.json file and both Debug and Release directories exist with newer assmblies in Release directory.

Repro:
Sepcify project assembly in Sergen.json file E.g  "Assemblies": [ "./bin/Debug/netcoreapp2.2/MyProject.dll"]. 
Compile in debug mode.
Switch to Release.
Modify an included file such as xxxform.cs.
Compile, changes will not be added to the xxxform.ts file.

Solution:
As per attached, look for "/bin/debug/" with the operating system's path separator character instead of hard coded directory separator.
Attached fix has been tested.

![bindebugissue](https://user-images.githubusercontent.com/39789524/76913728-def20a00-68f2-11ea-9272-7dc9a4512683.png)
[ServerTypingsCommand.cs.txt](https://github.com/volkanceylan/Serenity/files/4346372/ServerTypingsCommand.cs.txt)

Thanks again for a great system Volkan.

**Comment by volkanceylan** [comment]
Hmm, thanks yes there is a mistake there, index should be using same separator as os
