### ISSUE TITLE
Upgrading a fresh - working - demo project to .net core 3.1 throws Uncaught ReferenceError: <Projectname> is not defined

### ISSUE THREAD

**Issue by JohnRanger** [serenity-is/Serenity#4947]
Hi all,

I am trying to generate a .NET core 2.2 Serene demo app from 3.12.4 (I have fixed it so that it runs fine as a .NET core 2.2 app) and then manually upgrade it to .net core 3.1 by following these two guides:

https://serenity.is/docs/startsharp/updating-startsharp   (suggested by Volkan to do this first)
https://github.com/volkanceylan/Serenity/issues/4801 (the full upgrade guide by Volkan).

After that I cleaned and rebuilded the app - but I do get the following error after successfully passing the login screen and after the Dashboard is correctly shown:

![image](https://user-images.githubusercontent.com/2699447/78394068-3da1ce00-75eb-11ea-97a9-26e1fae71b15.png)

(where Serene1Core is my project's name).

The project compiles just fine without any error.

F12 debugging does not reveal much more information for this error:

![image](https://user-images.githubusercontent.com/2699447/78394426-f1a35900-75eb-11ea-8437-bf1f89a88967.png)

How can I fix this?

Any help is greatly appreciated.

With kind regards,

John

**Comment by JohnRanger** [comment]
Hi all,

just found the problem. When I was fixing the .NET core 2.2 Serene project by copying over the missing stuff under /wwwroot/content/... I accidentally did overwrite some of the already existing files. 

So when you do fix the .NET core V2.2 projects directly generated via the VS Marketplace Serene template by copying over missing stuff under content from a.NET full framework project, **do not overwrite** any diles.

Hope this helps someone.

With kind regards,

John

**Comment by ga5tan** [comment]
@JohnRanger - Sir, I've got the same problem (upgrading to latest MVC version.
What files do you think are causing this?
I was just updating nuget packages via VS interface
