### ISSUE TITLE
Bug: Sergen not listing SQLite tables, when |DataDirectory| path variable is used within connectionstring of solution

### ISSUE THREAD

**Issue by JohnRanger** [serenity-is/Serenity#4956]
Hi all, 

for a current project I have switched the DB backend from MS SQL to SQLite. So far, everything has worked out fine. The solution can access the SQLite DB without any problems. 

After following this excellent guide: https://volkanceylan.gitbooks.io/serenity-guide/sqlite.html - No errors are shown at sergen startup anymore (as it now finds the SQLite data provider).

But when I select my default connection string (which it successfully retrieves from the solution's web.config), no tables are listed.

In my case, the default connection key uses **|DataDirectory|** to dynamically find the path where the SQLite DB is located (in order to accommodate deployment to whatever sub directory structure on the target web server).

When I hard-code the path to the DB file within the connection string, then sergen is able to retrieve the tables.

Something like this (from SiteInitialization) would have to go into sergen:
```cs
dataFile = dataFile.Replace("|DataDirectory|", HostingEnvironment.MapPath("~/App_Data/"));
```
Where "~" is the same directory which sergen is already using to retrieve the connectionstring out of web.config of the solution.

How can sergen be motivated to use |DataDirectory|?

Any help is greatly appreciated.

With kind regards,

John

**Comment by volkanceylan** [comment]
|DataDirectory| should be handled by the MS SQL Provider, not Serenity.
