### ISSUE TITLE
Broken edit links in Drag & Drop Grouping tree branches

### ISSUE THREAD

**Issue by ghost** [serenity-is/Serenity#5238]
Hello, I want every branch and leaf of draggable groupin tree to link to its respective edit dialog. 

Branch/leaf of column "food" should link to FoodDialog, "customer" to CustomerDialog. 

Example of a branch:
![image](https://user-images.githubusercontent.com/66039631/94922627-de9a1480-04ba-11eb-8a47-2dd5a101fc67.png)

However, only edit links in the position of leaves do work. Branch links were either not generated at all or [Object object] was put as an ID parameter as on the following screenshot
![image](https://user-images.githubusercontent.com/66039631/94924713-59186380-04be-11eb-8cc1-5b9d7427b8b5.png)

Any ideas of what could've gone wrong? Thank you!

**Comment by volkanceylan** [comment]
Should use discussions.
