### ISSUE TITLE
[Announcement] Stackoverflow tag for Serenity Platform

### ISSUE THREAD

**Issue by VictorTomaili** [serenity-is/Serenity#5244]
Hello dear community,
As you know there is a lot of questions about serenity platform which got support from community. Also it's makes serenity issues dirty and we have hard time when we look for real serenity issues like bugs and requests. We want to clear other issues on serenity for just serenity related bugs, requests etc. For this reason we got a stackoverflow tag.
Currently, all of "How do I?" and "I got this error, why?" questions can be posted on stackoverflow with "serenity-platform" tag. https://stackoverflow.com/tags/serenity-platform

Also if you want to chat with someone about serenity and features, asking some questions etc. you can write on slack for that. 
For join  slack: https://join.slack.com/t/serenityplatform/shared_invite/zt-hz32q186-zqbk2QKj4UFLO3mJCtHNHQ
Slack: http://serenityplatform.slack.com

It's important for us to clear issues from questions because clear issues means more maintains, more new features and easy management on there.

When you really need to create an issue, please check issue guidelines before post an issue.
https://github.com/volkanceylan/Serenity/wiki/*Issue-Guidelines

Happy coding!

**Comment by JohnRanger** [comment]
Dear @VictorTomaili ,

Although I understand the reasoning of moving questions out of Github to SO - and many of  the real devs here have given thumbs up to this - I feel sad about it. The Serenity community was driving here in the "issues" - and the search within github is - IMHO - superior to the one on github.

Also, the Serenity community has a completely different style to help others compared with the "legalistic" Stackoverflow crowd - which often looks more to correct english grammar of the original post than to really help.

I am speaking of hard experience over there ;-)

Hope this will not keep of newcomers and veterans...

With kind regards,

John

**Comment by VictorTomaili** [comment]
Hi @JohnRanger,

I understand you and we need to focus issues first as you know. Don't worry our next step will be enabling [Github Discussion](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/) when we can.

**Comment by VictorTomaili** [comment]
Github Discussion is available now. 🎉
