### ISSUE TITLE
Bug; Sergen; MySQL column of type MEDIUMTEXT gets generated as of type StreamField instead of type StringField

### ISSUE THREAD

**Issue by JohnRanger** [serenity-is/Serenity#5260]
Hi @volkanceylan , @VictorTomaili ,

when generating code with sergen from a MySQL 8 table which includes a column of type MEDIUMTEXT then it is incorrectly created as StreamField when in fact it must be created with type StringField.

This is with latest SF (3.14.3) and latest MySQL (8.0.22).

The precise data type of a MySQL column can be easily retrieved with the following SQL command:

```sql
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH 
FROM information_schema.columns 
WHERE table_schema = '<DATABASE NAME>' 
AND table_name = '<TABLE NAME>' 
AND COLUMN_NAME = '<COLUMN NAME>'
```

With kind regards,

John

**Comment by chrisomeara** [comment]
LONGTEXT as well, I change all such field types to StringField after SERGEN and then all works well...

**Comment by volkanceylan** [comment]
@osmanaslancan could you please install MySql and check MEDIUMTEXT column.
