### ISSUE TITLE
cannot save record - "field is read only"

### ISSUE THREAD

**Issue by teafmartins** [serenity-is/Serenity#5312]
Hello,

I have background sevices that update discount field in order database table.
Field "Discount" in Row.cs is defined as "Updatable(false)", but when I save an order tha has changed discount field I get message "discount field is read only".

        [DisplayName("Discount"), DefaultValue(0), AlignRight, DisplayFormat("#,##0.00"), Updatable(false)]
        public Single? Discount
        {
            get { return Fields.Discount[this]; }
            set { Fields.Discount[this] = value; }
        }

![image](https://user-images.githubusercontent.com/17210232/102729267-f2218280-4327-11eb-9273-d3d248822ba8.png)

Is this a bug? shoudn't serenity bypass update of "discount" field?

Thanks for you help.

**Comment by VictorTomaili** [comment]
I transfer this question to discussion. 
You need clear assignment before save and before update in your order repository.
