### ISSUE TITLE
[BUG] -how to display image 

### ISSUE THREAD

**Issue by samaremad** [serenity-is/Serenity#5330]
i have problem that i upload image by [imageUploadEditer] (in the form) to the database but it didnt display instead of that in image column it appear as string location 

how can i solve this problem ?
![Screenshot (26)](https://user-images.githubusercontent.com/77009503/103657282-62f4ab80-4f72-11eb-8387-69bd07b87bc0.png)

**Comment by VictorTomaili** [comment]
It's not a bug. Please open a Q&A on discussion tab.
