### ISSUE TITLE
[BUG] - Exception occurs while code generation with sergen

### ISSUE THREAD

**Issue by tatronic** [serenity-is/Serenity#5335]
**Describe the bug**
I'm trying to generate code with Serenity Code Generator (ASP.NET Core) after a creation of migration class and generation of table in the database.

**To Reproduce**
1. Open a command prompt at project folder
2. Right click project name and click Open Folder in File Explorer
3. Click File menu in file explorer, and click Open Windows Powershell or Open Command Prompt
4. Type dotnet sergen g to open Sergen code generation UI (console).
5. You can use TAB completion, e.g. type D and press TAB to complete Default.
6. After pressing Enter you'll get a list of tables in that database
7. Enter the table name and press Enter
8. Enter module name and press Enter
9. Leave permission as Administration:General and press enter again
10. Sergen will ask you which files to generate, leave default RSUC option and press ENTER last time.

**Expected behavior**
Normally, after the steps above we should have a code generated in our visual studio solution

**Screenshots**
![image](https://user-images.githubusercontent.com/13600103/103767717-6d21b300-5021-11eb-938a-25072bacde34.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Microsoft visual studio 2019 version 16.8.3
 - Target framework : .Net 5.0

**Comment by VictorTomaili** [comment]
Can you run `dotnet sergen -v` on this directory?

**Comment by tatronic** [comment]
> Can you run `dotnet sergen -v` on this directory?

![image](https://user-images.githubusercontent.com/13600103/103772696-3a2fed00-502a-11eb-82f1-3ff8a8c70119.png)

**Comment by VictorTomaili** [comment]
Can you try with new version? 
https://www.nuget.org/packages/sergen/5.0.24

**Comment by tatronic** [comment]
> Can you try with new version?
> https://www.nuget.org/packages/sergen/5.0.24

All is good. Thanks
