### ISSUE TITLE
Unable to Call /Account/Login in  Serene ASP.NET Core

### ISSUE THREAD

**Issue by glenngsanchez** [serenity-is/Serenity#5342]
Hi All!

I started using Serene ASP.NET Core and trying to call Login API from external application.  Login is successful when calling Serene ASP.NET MVC, But this doesn't work when calling Serene ASP.NET Core **/Account/Login**.  I always get 404 Bad Request.  

POST http://localhost:59953/Account/Login http/1.1
content-type: application/json

{
    "Username": "admin", 
    "Password": "serene"
}

Please help/point me to the right solution. 

Thanks!

**Comment by VictorTomaili** [comment]
please use discussion for Q&A topics.
