### ISSUE TITLE
[HELP] - How to create Custom Attribute for Property Item

### ISSUE THREAD

**Issue by qubess** [serenity-is/Serenity#5347]
I want to create custom attribute data annotation for property item and its value should be accessible/reflect in typescript Slick.Column
For example:
HeaderCssClass
CssClass
Tab

Likewise, I want to create ColumnGroup property.

Your earliest support would be much appreciated.

**Comment by VictorTomaili** [comment]
@qubess for Q&A you can use Discussion on this repository. Please re-open this question on there.
