### ISSUE TITLE
Migration issues from Core 3 to 5.0.26

### ISSUE THREAD

**Issue by trueguy** [serenity-is/Serenity#5355]
I am not sure if this is related to migrations or not but I have gone from the .net core 3 version all the way to the 5.0.26 version using the instructions and ran into two problems.  

1. My sql connection is now erroring out while it had worked in .Net Core using 3.1.  The sql connection works fine for data tables within the main Serenity application db.  The error below points to a separate sql database connection and server.  

     Microsoft.Data.SqlClient.SqlException: 'A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)'

2. When running in the browser and view the console, there is an error that reference scripts in saltarelle, however the  migration instructions for 5.0.20 had us deleting that folder.
     GET http://localhost:55556/Scripts/saltarelle/mscorlib.js?v=2021011503 net::ERR_ABORTED 404 (Not Found)

Anyone had these issues?

Other than these two issues, everything seems to have gone smoothly.

**Comment by trueguy** [comment]
For issue 1.  Adding "TrustServerCertificate=True" to the connection string fixes the issue but is not a recommended solution.  Tried to run the previous version to compare if it's was a system changes that caused it but VS won't let me pick the Core 3.1 again so I can't run the previous version to compare.

**Comment by volkanceylan** [comment]
If you deleted mscorlib, you should delete it from bundles. The other error is related to Microsoft. Data. SqlClient and your server certificate, probably it raises a proper error while System. Data SqlClient ignored.

**Comment by trueguy** [comment]
Thank you deleted the reference in the bundle.

On last thing is there an equivalent to this?
(Dependency.Resolve<IAuthorizationService>() as ImpersonatingAuthorizationService).Impersonate("admin");

I know the new way is to use IUserAccessor but I am not sure.  Can you provide a same on how to impersonate the Admin and then undo?

Thanks.

**Comment by volkanceylan** [comment]
inject IUserAccessor, cast it to (IImpersonatingUserAccessor) and use as before

**Comment by trueguy** [comment]
in Startup.cs per migration
services.AddSingleton<IUserAccessor, UserAccessor>(); 

then
                    var prin = UserRetrieveService.CreatePrincipal(UserRetrieve, "Admin", "Windows");
                    (UserAccessor as IImpersonator).Impersonate(prin);

I think before it was just a simple user name but now it expects a ClaimsPrincipal object.  Is that how you go about it in Serenity .NET 5?

**Comment by volkanceylan** [comment]
Yes that's right, closing this, please use discussions
