### ISSUE TITLE
Error starting serene mvc project

### ISSUE THREAD

**Issue by zprofreelancer** [serenity-is/Serenity#5375]
Hello,
I'm using visual studio 2017 and have mssqllocaldb installed. But when i run the old serene mvc project, it issues "A network-related or instance-specific error occurred"
i checked the connection string in web.config file and it uses datasource localdb\mssqllocaldb. This should be correct.
So, what could be the problem?. please help

thanks.

**Comment by VictorTomaili** [comment]
Please use discussion instead issues. I close this.
