### ISSUE TITLE
[BUG] - Group elements in serenity dialog/form

### ISSUE THREAD

**Issue by vmrosariojoe** [serenity-is/Serenity#5394]
Hi, my screen dialog output appears like this : 
![20](https://user-images.githubusercontent.com/22878845/105698640-1aad2580-5f41-11eb-9cde-68e9d9612e17.PNG)
![21](https://user-images.githubusercontent.com/22878845/105698358-bab67f00-5f40-11eb-889b-b061fdef606a.PNG)

I want the UI to group the elements and appear like below : 
![22](https://user-images.githubusercontent.com/22878845/105698409-cdc94f00-5f40-11eb-8e30-1ae64e4fd6e2.PNG)
![23](https://user-images.githubusercontent.com/22878845/105698430-d4f05d00-5f40-11eb-96e9-a13f109d450c.PNG)
How to achieve this in my form/dialog with css attributes?

**Comment by VictorTomaili** [comment]
Hey @vmrosariojoe as you see this is issue tab for about bugs etc. But you have question instead. Please use discussion for Q&A related topics. I close this.
