### ISSUE TITLE
make a checkbox by default checked 

### ISSUE THREAD

**Issue by amirkian** [serenity-is/Serenity#5401]
I made a filed in SQL server that name was success and field type was bit then made a Boolean field corresponding to this field in the form.
so far I have such this line of code 

```
        [Visible(true),Width(132)]
        
        public Boolean Success { get; set; }
```

as result I have a checkbox .

![image](https://user-images.githubusercontent.com/19525693/105963049-c1a2d600-6095-11eb-86d0-19a27a33b12f.png)

All of thing that I want is this checkbox be checked by default.

**Comment by VictorTomaili** [comment]
Hi @amirkian, please use discussion for Q&A. I close this because of not an issue
