### ISSUE TITLE
How to add inline button for each grid rows when click on it , update some field in dialog 

### ISSUE THREAD

**Issue by waleed51** [serenity-is/Serenity#5409]
I want to add inline button for each grid rows when click on it , update some field in dialog related to this row. 

- for example : I have grid contain visits transaction,  this grid (like photo) , 

-  I want when I click on this blue button for any row , then update the field (Time Out) and field (State) for this Row, like when I modify it from dialog panel.
 
and thank you.

![Screenshot_2](https://user-images.githubusercontent.com/18492471/106296285-23ac3880-625a-11eb-806e-9301618c76ee.png)

**Comment by VictorTomaili** [comment]
Hello @waleed51 
Please use Discussion for Q&A related topics instead issues. I close this.

**Comment by waleed51** [comment]
can i know why ? @VictorTomaili

**Comment by VictorTomaili** [comment]
Because this is not an issue. And all community uses discussion tab for questions and answers.

**Comment by waleed51** [comment]
ok , thank you @VictorTomaili

**Comment by VictorTomaili** [comment]
Thank you for understanding 👍

**Comment by waleed51** [comment]
u r welcome
