### ISSUE TITLE
Solving a big Delay when use a lookup for more 70,000 rows !

### ISSUE THREAD

**Issue by waleed51** [serenity-is/Serenity#5414]
I have a (Visits) grid which records visits transactions to my company ,
and it have a relation with (Visitor) -Visit have one or more visitors- ,

I use a Visitors Row as Lookup in Visit dialog, to can select visitor when I add a new Visitor transaction, ( like in Picture).

the problem is Visitor table have more 70,000 rows, when I use it in lookup it make a big delay for searching on it to retrieve data.

Is there is any way to not load all lookup, only load based on search in lookup, or any alternative option compatible with my business?

![Screenshot_3](https://user-images.githubusercontent.com/18492471/106301166-0ed2a380-6260-11eb-9ef7-f6ae3e243bb2.png)

**Comment by kilroyFR** [comment]
There is an option to load lookup asynchronously

**Comment by waleed51** [comment]
Please more explanation @kilroyFR
