### ISSUE TITLE
Stargen tool

### ISSUE THREAD

**Issue by HariPrasadIT** [serenity-is/Serenity#5418]
Hi,

We have purchased Serenity Premium (Personal, 12 Months) license and wants to upgrade .net core 3.1 app to 5. According to this article https://serenity.is/docs/migration/v3-to-v5, we can use stargen tool to upgrade, but in our serenity.is login we could not find this tool to download, where can we download this tool...

Thanks..

**Comment by VictorTomaili** [comment]
You say "We have purchased" and personal license for just for one person. If you have access to startsharp repository, you can download it from there. But we didn't see your account as premium user. Also you already send documentation link what included download link for stargen.
