### ISSUE TITLE
Edit button NOT DISABLED on LookupEditors of ReadOnly Dialog 

### ISSUE THREAD

**Issue by kilroyFR** [serenity-is/Serenity#5419]
hey there, i noticed something recently (on last 3.14.x) serenity version.

i have a dialog with some lookupEditor fields (addInPlace = true).
When i set this dialog as readonly using :  `Serenity.EditorUtils.setReadonly(this.element.find('.editor'), true);` in updateInterface() of the Dialogxxx.ts, i noticed a strange behavior on the lookup editor fields.

For the ones that have a selected value the 'Edit button' is available and can be clicked => not correct behavior
For the ones that have no selected value the 'Add button' is not available => correct behavior

Please see screenshot

![image](https://user-images.githubusercontent.com/31513956/106365771-02217e80-6338-11eb-8515-bb142d5d7721.png)

**Comment by VictorTomaili** [comment]
First one selected value also can be edited at on own screen. It's mean you can edit this data already. Second editor is not filled so you can't create new record and select it. There is no strange behavior.
