### ISSUE TITLE
Update Record - xyz field on xyzRow is read before assigned a value!

### ISSUE THREAD

**Issue by trackitaero** [serenity-is/Serenity#5434]
Hi,

Converted serenity MVC to .net core 5 version, insert on FlightPlan table works fine, but update is giving error. We have FlightPlan and Assets tables which are mapped to GSEAllocation table with many to many relationship. In FlightPlanRow we have

[DisplayName("Allocated GSE")]
[LookupEditor(typeof(AssetMasterRow), Multiple = true), NotMapped]
[LinkingSetRelation(typeof(GseAllocationRow), "FlightPlanId", "AssetId")]
[MinSelectLevel(SelectLevel.Details), QuickFilter(CssClass = "hidden-xs")]
public List AllocatedGseList
{
get => fields.AllocatedGseList[this];
set => fields.AllocatedGseList[this] = value;
}

While updating a row in FlightPlan we are getting this error

AllocatedGseList field on FlightPlanRow is read before assigned a value! Make sure this field is selected in your SqlQuery. Extensions like connection.List only loads table fields by default, view / expression fields are not loaded unless explicitly selected.

Please suggest..

**Comment by VictorTomaili** [comment]
duplicated on startsharp repository. We answered there. I close this.
