### ISSUE TITLE
[BUG] - sergen code generator object reference not set for azure sql simple table- addfield to error

### ISSUE THREAD

**Issue by swiftinitdotcom** [serenity-is/Serenity#5435]
I have azure sql with simple 2 tables and when I do sergen and try to generate code it shows tables but shows this error. I have trial serenity download.

**Comment by VictorTomaili** [comment]
@swiftinitdotcom can you edit details?

**Comment by swiftinitdotcom** [comment]
Added it its object reference not set world famous error

**Comment by VictorTomaili** [comment]
we need other details, sergen version, azure sql version, table details, serene version, serenity version, steps for reproduce etc. And you can delete rest of description what not related to issue like browser version etc.

**Comment by swiftinitdotcom** [comment]
https://marketplace.visualstudio.com/items?itemName=VolkanCeylan.SereneSerenityApplicationTemplate

Version | 5.0.24.0 |  
-- | -- | --
Released on | 11/4/2014, 6:13:15 PM |  

Last updated | 1/6/2021, 9:09:05 PM |  
Publisher | Volkan Ceylan

Azure sql -sql server 12.0

**Comment by swiftinitdotcom** [comment]
Just create azure sql table and create serene template app in vs 2019 and try to generate code form tables- gives this not set error....

**Comment by swiftinitdotcom** [comment]
I can show you the error, we are trying to use new tools and see if this works, first step is to make it run.

**Comment by volkanceylan** [comment]
not enough details

**Comment by swiftinitdotcom** [comment]
I think I provided enough details. Version azure and all other details. Anyway dropping this tool from exploration as first step itself does not work and no one to resolve it...

**Comment by swiftinitdotcom** [comment]
Good amount of details provided. Going for another tool. Thanks.
