### ISSUE TITLE
The sergen 5.0.36 package is not compatible with net5.0

### ISSUE THREAD

**Issue by juliermefelix** [serenity-is/Serenity#5438]
When trying to install sergen 5.0.36 I get the error message stating that it is not compatible with net5.
how to solve?

![image](https://user-images.githubusercontent.com/7516443/107030050-c4d14c80-678e-11eb-985b-812714455350.png)

Error:
Error NU1202 The sergen 5.0.36 package is not compatible with net5.0 (.NETCoreApp, Version = v5.0). The sergen 5.0.36 package supports: net5.0 (.NETCoreApp, Version = v5.0) / any

**Comment by VictorTomaili** [comment]
It's dotnet tool, not a nuget package what you can use in your project. You need to use it from command line. 

use this command for install which written in nuget repository https://www.nuget.org/packages/sergen/
`dotnet tool install --global sergen --version 5.0.36`
