### ISSUE TITLE
Help regarding permissions 

### ISSUE THREAD

**Issue by vinaysalian** [serenity-is/Serenity#5441]
Can permissions be assigned heirarchly in roles ?
For example : There are three roles admin, Supervisor, user
There are three Pages X , Y, Z.
If admin and supervisor have access to role managemnt .
And admin assigns supervisor  Read and write access permissions  to Pages Y and Z and denies access permissions to page  X.

So when supervisor accesses Role managemnt he should only be able to assign Read /write permissions to User for pages Y and Z .but not  X .

Please help how this can be acheived

**Comment by VictorTomaili** [comment]
@vinaysalian please use [Discussion](https://github.com/serenity-is/Serenity/discussions) for questions. I close this. Thank you.
