### ISSUE TITLE
Road Map - Master detail, Audit actions, Rapid Generator, Maps

### ISSUE THREAD

**Issue by weedkiller** [serenity-is/Serenity#5444]
Hello, the demo does not have some features and I did not see this in the roadmap. I think a lot of this is in various competing products, would be nice to have Road Map

1. Master-Details 
2. Audit action
3. [Rapid Gen tools](https://docs.aspnetzero.com/en/common/latest/Rapid-Application-Development)
4. Dashboard widgets with setting (Copy, Print, Export)
5. Maps

**Comment by VictorTomaili** [comment]
@weedkiller Most of this features are premium or will be premium. Also please use [Discussion ](https://github.com/serenity-is/Serenity/discussions) for questions etc.

**Comment by JohnRanger** [comment]
@weedkiller ,

Serenity Framework **has** an excellent, rapid gen tool: sergen. Check it out :-)

With kind regards,

John
