### ISSUE TITLE
RowIndexFormatter.ts not found in AspNet Core

### ISSUE THREAD

**Issue by TechAspirant** [serenity-is/Serenity#5449]
I am getting error in the application as below

![image](https://user-images.githubusercontent.com/40688461/107150088-1130ae00-6982-11eb-9196-ccd992036176.png)

I am building my application via dotnet CLI. RowIndexFormatter.ts file do exists in ..\..\Modules\Common\Helpers

**Comment by VictorTomaili** [comment]
Serenity doesn't has RowIndexFormatter.ts file or similar code in common\helpers. It is a code given as an example in some Issues. Check [this issues](https://github.com/serenity-is/Serenity/search?q=RowIndexFormatter&type=issues) first.
