### ISSUE TITLE
Serenity 5 email configuration

### ISSUE THREAD

**Issue by Judhianto** [serenity-is/Serenity#5461]
Hi!

I want to implement email notification, but i found in SmtpSettings, there is no field for password. Since my email server need authorization, i always get error message when apps tried to send email -- "5.7.1 <abc@xyz.com> : Sender address rejected: not logged in"

My question: Where i can put password information for the smtp connection?

thank you

    public class SmtpSettings
    {
        public const string SectionKey = "SmtpSettings";
        public string Host { get; set; }
        public int Port { get; set; }
        public bool UseSsl { get; set; }
        public string From { get; set; }
        public string PickupPath { get; set; }
    }

**Comment by VictorTomaili** [comment]
Create your own [MailSender](https://github.com/serenity-is/Serene/blob/master/Serene/Serene.Core/Modules/Common/EmailSender/EmailSender.cs) for your requirements. 

Please use [Discussions](https://github.com/serenity-is/Serenity/discussions) for questions.

**Comment by VictorTomaili** [comment]
[MailSender](https://github.com/serenity-is/common-features/blob/1150dade4c1d311ff91919d9ce82ec21b079fbcf/src/Serenity.Extensions/Serenity.Extensions/EmailSender/EmailSender.cs) moved to the common samples repository
