### ISSUE TITLE
[BUG] - CodeGenerator fail to transform ts files with kendo.all.d.ts in typings folder

### ISSUE THREAD

**Issue by Armed79** [serenity-is/Serenity#5462]
- [x] This isn't a feature request or a discussion topic
- [x] I have searched open and closed issues for duplicates
- [x] I am searched documents on https://serenity.is/docs/
- [ ] I have read https://serenity.is/docs/startsharp/faq
- [x] I have to use descriptive issue title
- [x] I approve to fill in the information below
 
**Describe the bug**
I use telerik jquery UI library, and need to use kendo.all.d.ts in typings folder. But this file will make the code generator(v5.0.36) stop to work. When I remove this typing file, the transform proccess will wor.

The exception is as below:

1>Transforming MVC at: .\Imports\MVC
1>System.IO.FileNotFoundException: Could not find file 'C:\Users\maxson\AppData\Local\Temp\tmp1FA1__\typeList.json'.
1>File name: 'C:\Users\maxson\AppData\Local\Temp\tmp1FA1__\typeList.json'
1>   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
1>   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
1>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
1>   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
1>   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
1>   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
1>   at System.IO.File.ReadAllText(String path)
1>   at Serenity.CodeGenerator.TSTypeLister.List()
1>   at Serenity.CodeGenerator.Program.<>c__DisplayClass1_0.<Run>b__0() in C:\Sandbox\StartSharp\Serenity\src\Serenity.Net.CodeGenerator\Program.cs:line 90
1>   at Serenity.CodeGenerator.Program.Run(String[] args, IFileSystem fileSystem, Func`1 projectSystemFactory) in C:\Sandbox\StartSharp\Serenity\src\Serenity.Net.CodeGenerator\Program.cs:line 108

[kendo.all.d.zip](https://github.com/serenity-is/Serenity/files/5950972/kendo.all.d.zip)

**Comment by VictorTomaili** [comment]
Add exclude lines to your `sergen.json` and use latest sergen.

```
  "Restore": {
    "Exclude": [
      "/wwwroot/Scripts/kendo/kendo*.*"
    ]
  }
```

**Comment by Armed79** [comment]
The setting is not work for this issue.
 I check the soure, and found that issue is cause by the List function in class TSTypeLister.  And this step do not check the sergen.json setting.
And when kendo.all.d.ts exist, List function will generate index,js file for node to run, but it failed with execption, so no typeList.json file is gereated by node.

**Comment by VictorTomaili** [comment]
Sorry, I provided wrong exclude code. Can you try to exclude it from `tsconfig.json`?

```json
    "Exclude": [
      "/wwwroot/Scripts/kendo/kendo*.*"
    ]
```

**Comment by Armed79** [comment]
The Exclude config in tsconfig.json work! 
I need to include the d.ts file for intellisense, and exclude it for transform compile.
Thank you for the solution!
