### ISSUE TITLE
[BUG] - Content Security Policy Headers- Browser complaints about inline scripts, application fails.

### ISSUE THREAD

**Issue by mgbadia** [serenity-is/Serenity#5468]
**Describe the bug**
Application fails when Content Security Policy headers are included.
**To Reproduce**
Add the following to the _Layout.cshtml:

    <meta http-equiv="Content-Security-Policy"
          content="base-uri 'self';
          connect-src 'self' ;
          default-src 'self' ;
          font-src 'self' ;
          frame-src 'self' ;
          img-src data: 'self' ;
          manifest-src 'self' ;
          media-src 'self' ;
          object-src 'none' ;
          script-src 'self' ;
          style-src 'self' ;
          worker-src 'none';
          upgrade-insecure-requests;"/>

**Additional context**
Sergen generates inline scripts, but I can move that to a separate file.
There are inline scripts generated by the app as:
<script type="text/javascript">
window.paceOptions = { startOnPageLoad: false, ajax: { trackMethods: ['GET', 'POST'], trackWebSockets: false, ignoreURLs: [] } };</script>

<script type="text/javascript">
    Q.ScriptData.set('Lookup.Administration.Language', new Q.Lookup({"idField":"LanguageId","textField":"LanguageName"}, 
[{"Id":6,"LanguageId":"zh-CN","LanguageName":"Chinese (Simplified)"},{"Id":1,"LanguageId":"en","LanguageName":"English"},{"Id":10,"LanguageId":"fa","LanguageName":"Farsi"},{"Id":5,"LanguageId":"de","LanguageName":"German"},{"Id":7,"LanguageId":"it","LanguageName":"Italian"},{"Id":8,"LanguageId":"pt","LanguageName":"Portuguese"},{"Id":9,"LanguageId":"pt-BR","LanguageName":"Portuguese (Brazil)"},{"Id":2,"LanguageId":"ru","LanguageName":"Russian"},{"Id":3,"LanguageId":"es","LanguageName":"Spanish"},{"Id":4,"LanguageId":"tr","LanguageName":"Turkish"},{"Id":11,"LanguageId":"vi-VN","LanguageName":"Vietnamese (Vietnam)"}]
));
    
.. etc
All these inline scripts will impact enforcing CSP. Any suggestions?
Thanks!

**Comment by VictorTomaili** [comment]
Can you report this issue to slick grid repository? It's doesn't related to serenity. I close this, thank you.
