### ISSUE TITLE
I am attempting to use vue version 3 but the current version of Serentiy.CoreLib.js currently only works with version 2.  

### ISSUE THREAD

**Issue by anthonywisbith** [serenity-is/Serenity#5473]
I am trying to create a page within my site that will be using version 3 of Vue.  I'm not using view any were else in the website.  The problem is that the vueIntegration() method in the Serentiy.CoreLib.js detects that Vue is being used and tries to integrate with it.  Unfortunate the code is written to only work with an old version of Vue.  A lot of changes were made to Vue in the version 3 release and the Serenity code is not compatible with the current version of Vue.  Basically Serenity is effectively hard coded to a old version of Vue.

The error that is received is "Vue.component is not a function"

The error can be recreated by importing the current version of Vue on any page using the following line:

<script src="https://unpkg.com/vue@next"></script>
 

Two possible solutions would be for the Serentiy.CoreLib.js code to detect the version of Vue being used or provide a method to turn off the automatic integration.

**Comment by volkanceylan** [comment]
insert a dummy file containing a code like below between vue and corelib

Vue.component = function() {}

**Comment by anthonywisbith** [comment]
That worked thanks!
