### ISSUE TITLE
How can i pass value from parent dialog to child dialog

### ISSUE THREAD

**Issue by mussabnet** [serenity-is/Serenity#5474]
how can i send value from parnet dialog to child dialog

![togithub](https://user-images.githubusercontent.com/25321607/107874040-707d4980-6ebf-11eb-8df3-4a25ca102274.PNG)

**Comment by mussabnet** [comment]
@volkanceylan

**Comment by VictorTomaili** [comment]
@mussabnet please use [Discussions](https://github.com/serenity-is/Serenity/discussions) for questions.
