### ISSUE TITLE
How can i pass value from parent dialog to child dialog

### ISSUE THREAD

**Issue by mussabnet** [serenity-is/Serenity#5475]
How can i pass value from parent dialog to child dialog
![togithub](https://user-images.githubusercontent.com/25321607/107875639-cbb43980-6ec9-11eb-8eba-363367779297.PNG)

**Comment by mussabnet** [comment]
@volkanceylan

**Comment by VictorTomaili** [comment]
@mussabnet use discussion for questions. Please don't bother anyone in weekend. Also you can find solution if you search in this repository old discussions and issues. 
Don't open issues for your personal questions. Serenity and Serene supported by community. You need to wait answer from community. Startsharp and Premium support also available if you buy. But premium packages provide support in work hours too.
