### ISSUE TITLE
The Form design differs if I change the language to Arabic or Farsi

### ISSUE THREAD

**Issue by Mohamed-Ali-Salim** [serenity-is/Serenity#5489]
This picture is in the default mode, which is the English language, see Section 1 to find that each field is in a row separately, and Section No. 2 too

![Screenshot (215)](https://user-images.githubusercontent.com/52743515/108037133-d42f8000-7041-11eb-9348-61ddb60e7938.png)

But look at the second picture,  when I changed the language to Farsi, Section No. 1 became all the fields in the same row and  Section No. 2 too

![Screenshot (216)](https://user-images.githubusercontent.com/52743515/108037738-b0b90500-7042-11eb-9a0b-13a1da5baef4.png)

**Comment by VictorTomaili** [comment]
Please use [Discussions](https://github.com/serenity-is/Serenity/discussions) for questions. 
Your problem related to right to left css "rtl.css" what may need some custom css for your form.
