### ISSUE TITLE
Multiple Simultaneous Dialogs Mode 

### ISSUE THREAD

**Issue by mjacoup** [serenity-is/Serenity#5506]
Thanks Volkanceylan for this great platform 
A client asked us to enable open more than windows (dialogs) in the same time and can minimize , activate and activate any window ( dialog) because they are currently make this by open tabs in browsers . I see it is logic requirement and wonder is serenity handle this mode in basic or advanced samples ? if no how can i do this ?  

Thanks in advance

**Comment by VictorTomaili** [comment]
Please use[ discussions](https://github.com/serenity-is/Serenity/discussions) for questions requests etc. except issues.
