### ISSUE TITLE
CKEditor Error in Serenity 5 when ScriptBundling Enabled true

### ISSUE THREAD

**Issue by newyearsoft** [serenity-is/Serenity#5591]
CKEditor Error in Serenity 5 when ScriptBundling Enabled true

**Comment by VictorTomaili** [comment]
Do you checked [this discussion](https://github.com/serenity-is/Serenity/discussions/5433)? Please search old issues and discussions before open an issue. Also please use detailed issue template and fill all information if you really need to open an issue.
