### ISSUE TITLE
Serenity NavigationLink doesnt work after publish on IIS

### ISSUE THREAD

**Issue by hafizTahir** [serenity-is/Serenity#5596]
after publishing on IIS its base address is not include in navigation that causes error:

Navigation.cs :
[assembly: NavigationMenu(int.MaxValue, "AMSDB", icon: "fa-laptop")]

[assembly: NavigationLink(int.MaxValue, "AMSDB/Category", typeof(MyPages.CategoryController), icon: null)]
![1](https://user-images.githubusercontent.com/39436753/112628282-7ec26c00-8e54-11eb-8990-2691811308ef.png)

**Comment by VictorTomaili** [comment]
Did you miss this? https://github.com/serenity-is/Serenity/discussions/5595#discussioncomment-528942

Our demo application works like that and there is no issue about this. Just missing configuration I believe. 
I close this.
