### ISSUE TITLE
MasterDetailRelation Save Error

### ISSUE THREAD

**Issue by mrokicki-dev** [serenity-is/Serenity#5602]
I followed the MasterDetail examples in the documentation and Northwind DB, but the record is looking for the parent ID and will not save without it.

I tried overriding the SetInternalFields on the WorkFlowRepository and manually setting the WorkFlowId for each item in the Milestones list. This gets past the validation error, but deletes all the child records every time a new record is updating.

I tried to fix this by 
![SerenityMasterDetailError](https://user-images.githubusercontent.com/77282876/112911025-fd95fe00-910d-11eb-8d02-6c7286dea97c.PNG)

**Comment by VictorTomaili** [comment]
@mrokicki-dev please use discussions for questions.
