### ISSUE TITLE
Get current user id or username in serenity core.net5

### ISSUE THREAD

**Issue by abualmazen** [serenity-is/Serenity#5616]
how i can get current userid or username in model Repository
i try to use this code :  var user = (UserDefinition)Authorization.UserDefinition;
but it give error . 
thanks .

**Comment by karimhyatt** [comment]
Use the Context for User info

User Id: 
`Context.User.GetIdentifier()`
User Name: 

User Name:
`Context.User.Identity.Name`

**Comment by VictorTomaili** [comment]
Please use discussion for Q&A

**Comment by amkh1900** [comment]
How i can get current userid or username  or dispayName in **Controller** page 
i try to use this code : var user = (UserDefinition)Authorization.UserDefinition;
                                  AND var user = Context.User.Identity.Name;
but it give error . i WORK SERENITY CORE
thanks .

**Comment by VictorTomaili** [comment]
search it in discussions @amkh1900
