### ISSUE TITLE
Sorting drop down lists by ID instead of description

### ISSUE THREAD

**Issue by shortsam1** [serenity-is/Serenity#5625]
I am new to serenity and .net core. I am using the latest .net core SDK 5.0 and the latest version of serenity.  I am trying to sort the month drop down list by the ID field instead of by the description.  Any help is greatly appreciated.  This is the current drop down list.  I would like to sort it by the MonthID field instead.  

![image](https://user-images.githubusercontent.com/47765946/114372606-16e68200-9bc5-11eb-850c-005a7035e27c.png)

The tablerow.cs is listed as follows:

```
        [DisplayName("Month"), Column("MonthID"), ForeignKey("[online_form].[Ref_Month]", "MonthID"), LeftJoin("jMonth"), TextualField("MonthShortDesc")]
        [LookupEditor(typeof(RefMonthRow))]
        public Int32? MonthId
        {
            get => fields.MonthId[this];
            set => fields.MonthId[this] = value;
        }

```
The monthrow.cs is

```
        [DisplayName("Month Id"), Column("MonthID"), Identity, IdProperty, SortOrder(1)]
        public Int32? MonthId
        {
            get => fields.MonthId[this];
            set => fields.MonthId[this] = value;
        }
```

**Comment by VictorTomaili** [comment]
Please use discussions
