### ISSUE TITLE
Hide list form on startup and add edit button next to new button to display list form.

### ISSUE THREAD

**Issue by shortsam1** [serenity-is/Serenity#5626]
I am new to serenity and .net core. I am using the latest .net 5.0 and the latest version of serenity. 

Here is a copy of the form I am in the process of writing.
![image](https://user-images.githubusercontent.com/47765946/114377025-8bbbbb00-9bc9-11eb-83a5-d2f675cafdf7.png)

I have been asked to hide the list form (purple box) on startup of our system and only show the heading, search box and 3/4 buttons at the top (red box).  As I am new to this, I have not been able to work this out and I am on a tight deadline.

They also would like to have a "Edit Report" button (pink text) at the top next to the "New Report" button.  On click of this button they would like to display the list form (purple box) that is currently displayed in the pic above

All help is greatly appreciated as I am on a really tight deadline.

**Comment by VictorTomaili** [comment]
Please use discussions
