### ISSUE TITLE
 AdminLTE and Bootstrap 4 update

### ISSUE THREAD

**Issue by ArsenioInojosa** [serenity-is/Serenity#5646]
Hello everybody,

Is the AdminLTE update planned in the future? AdminLTE already uses Bootstrap 4. [https://github.com/ColorlibHQ/AdminLTE](url)

Thanks

**Comment by VictorTomaili** [comment]
We don't have any plan about update AdminLTE currently. We are open for PR request for serene template. 
And please use discussions for not bug related topics.
