### ISSUE TITLE
how can create shows questions and options on a grid with radio button

### ISSUE THREAD

**Issue by hosnabigdeli** [serenity-is/Serenity#5680]
hi 
I'm trying to design a questionnaire that shows questions and options on a grid
I displayed the questions and options with Group and added a radio button column. How can I group these radio buttons to be answered for each question ???
Thanks

this my code---->

` export class QuestionOptionsGrid extends QuestionOptionsGridBase {
        private radRowSelection: Serenity.GridRadioSelectionMixin;
        constructor(container: JQuery) {
            super(container);

        }
        protected onViewSubmit() {
            this.view.setGrouping(

                [{

                    formatter: x => ' Question: ' + x.value,

                    getter: fld.QuestionTitle
                    // getter: 'QuestionId'

                }  ]

            );

            return true;
        }

protected createToolbarExtensions() {
            super.createToolbarExtensions();
            this.radRowSelection = new Serenity.GridRadioSelectionMixin(this);
        }
 protected getColumns() {
            var columns = super.getColumns();
            columns.splice(0, 0, Serenity.GridRadioSelectionMixin.createSelectColumn(() => this.radRowSelection));
          

            return columns;
        }

`

**Comment by VictorTomaili** [comment]
Please use discussions instead issues.
