### ISSUE TITLE
Serene 5.0.24.0 can not build solution after generating site

### ISSUE THREAD

**Issue by minhhungit** [serenity-is/Serenity#5682]
**Describe the bug**
as title it generate dashboardPage.cs like image, and cause build error
this is code is generated

![image](https://user-images.githubusercontent.com/2279508/116780557-ba7dd080-aaa7-11eb-867b-f21f3f4a6091.png)

**To Reproduce**

Uncheck all options on wizard

![image](https://user-images.githubusercontent.com/2279508/116783001-8231be80-aab6-11eb-83b2-bf2b2a2c8e46.png)

**Comment by VictorTomaili** [comment]
Please use bug report template and fill all information about your issue. 
https://github.com/serenity-is/Serenity/issues/new?assignees=VictorTomaili&labels=waiting-for-check&template=bug_report.md

**Comment by minhhungit** [comment]
I see that if I uncheck all checkbox then it has error

![image](https://user-images.githubusercontent.com/2279508/116780765-c28a4000-aaa8-11eb-8dff-8123f928c069.png)

If I let it as default with all options are selected then it's okay

**Comment by minhhungit** [comment]
@VictorTomaili I updated

**Comment by VictorTomaili** [comment]
What about versions ?
**Serenity Versions
 - Serene Template Version (when reproduced on Serene Template)
 - Sergen Version (if required)
 - Installed Serenity Nuget Packages Versions (you can find them in csproj)

**Comment by minhhungit** [comment]
@VictorTomaili here is more information, thanks

Serene template version is 5.0.24.0
sergen          5.0.24 
nothing change with nuget package version

**Comment by minhhungit** [comment]
Btw you should put **Serenity Versions** to top of the bug report template :)

**Comment by VictorTomaili** [comment]
I can't reproduce it, what is your namespace, visual studio version, any other working environment configuration what can cause this.

**Comment by minhhungit** [comment]
I uninstall and re-install version 5.0.24 but still getting the issue

It looks if we create project that has "**Serenity**" string in namespace it will cause error, for example my namespace is "TestSerenityDemo"

**Comment by minhhungit** [comment]
I use Microsoft Visual Studio Enterprise 2019 Version 16.9.2
I also has Serene MVC version (obsolete) installed on my computer

**Comment by minhhungit** [comment]
@VictorTomaili I think I can reproduce it
I re-installed windows OS, re-installed visual studio 2019 (Version 16.9.4)

I installed Serene extensions (both Serene .net core & ASP.NET MVC - Obsolete) => no error
But after installing startsharp extension 5.0.26.0 and create Serene project with solution name `SomeSerenityApp` I got the issue

If create project using Startsharp template => no issue

**Comment by VictorTomaili** [comment]
Okay, just don't use serenity in namespace currently. I already removed waiting-for-check tag from this issue.

**Comment by YoselYohan** [comment]
The issue you are having is with the regular Serenity (Not StartSharp) when creating an empty solution (unchecking all). The error is on file DashboardController.cs. The class generated should be...

`
using Microsoft.AspNetCore.Mvc;
using Serenity;
using Serenity.Abstractions;
using Serenity.Data;
using Serenity.Web;
using System;

namespace yourNameSpace.Common.Pages
{
    [Route("Dashboard/[action]")]
    public class DashboardController : Controller
    {
        [PageAuthorize, HttpGet, Route("~/")]
        public ActionResult Index(
            [FromServices] ITwoLevelCache cache,
            [FromServices] ISqlConnections sqlConnections
            )
        {
 public ActionResult Index()
        {
  
            return View(MVC.Views.Common.Dashboard.DashboardIndex, new DashboardPageModel());
      }
    }
  }
}
`

**Comment by VictorTomaili** [comment]
resolved
