### ISSUE TITLE
serenity ------> select row with radio button

### ISSUE THREAD

**Issue by hosnabigdeli** [serenity-is/Serenity#5685]
hey 
I have a column of radio buttons in the grid
How to get the value  of that row from the table where the radio button was checked.

this my code (for show radio button in grid):
 protected createToolbarExtensions() {
            super.createToolbarExtensions();
            this.radRowSelection = new Serenity.GridRadioSelectionMixin(this);
        }

    

        protected getColumns() {
            var columns = super.getColumns();
            columns.splice(0, 0, Serenity.GridRadioSelectionMixin.createSelectColumn(() => this.radRowSelection));
        
            return columns;
        }
![44444444](https://user-images.githubusercontent.com/56981629/116843546-86b0c100-abf5-11eb-9733-3eaf43e123df.PNG)

**Comment by VictorTomaili** [comment]
Please use discussions @hosnabigdeli
