### ISSUE TITLE
Reports and Multi Tenant - seems to bypass the behaviours

### ISSUE THREAD

**Issue by bigjezza** [serenity-is/Serenity#5691]
Hi, 
I'm using Serenity 3.14 and I've followed the Multitenancy tutorial - all seems well with casual usage.

However I've just discovered that I can call a report from the console and retrieve data from the other tenant. Did I miss something?

**Comment by bigjezza** [comment]
Holdup I stepped away from my desk and had a think. It might be because my custom reports are using an SQL connection and I havent included a .Where
I'll go play and update this soon

**Comment by VictorTomaili** [comment]
@bigjezza please use discussions.
