### ISSUE TITLE
bootstrapMessages = true & Entity Dialog Delete (3.14.5)

### ISSUE THREAD

**Issue by bigjezza** [serenity-is/Serenity#5707]
<img width="498" alt="Screenshot (121)" src="https://user-images.githubusercontent.com/71537925/117784339-9d54b900-b282-11eb-8ede-d582a705b0cc.png">
Hi,
If I set
bootstrapMessages = true

and open an entity dialog, and press Delete, the bootstrap dialog to confirm the delete is grayed out and I'm unable to click it.

**Comment by VictorTomaili** [comment]
Can you fill all required fields on form when you create a new issue?

**Comment by VictorTomaili** [comment]
I close this, because of not enough information. If you want report this issue again, create new "[Bug Report](https://github.com/serenity-is/Serenity/issues/new/choose)" and please ensure about all required fields must be filled.
