### ISSUE TITLE
DecimalEditor MaxValue = "0" no longer works

### ISSUE THREAD

**Issue by MagDev175** [serenity-is/Serenity#5846]
**Describe the bug**
I used to have this line in the to make a negative only value: [DecimalEditor(MinValue = "-99", MaxValue = "0", Decimals = 4)]. Now this prevents all values except 0.

**To Reproduce**
Add [DecimalEditor(MinValue = "-99.99", MaxValue = "0", Decimals = 4, AllowNegatives = true)] to the Row Class. No values possible. Removing the MaxValue="0" will allow negative numbers but unfortunately also positive numbers.

**Expected behavior**
Allowed values between -99 and 0.

**Serenity Versions
  <package id="Serenity.CodeGenerator" version="3.9.14" targetFramework="net47" />
  <package id="Serenity.Core" version="3.9.14" targetFramework="net47" />
  <package id="Serenity.Data" version="3.9.14" targetFramework="net47" />
  <package id="Serenity.Data.Entity" version="3.9.14" targetFramework="net47" />
  <package id="Serenity.Pro.Scripts" version="5.0.26" targetFramework="net48" />
  <package id="Serenity.Pro.UI" version="5.0.42" targetFramework="net48" />
  <package id="Serenity.Scripts" version="5.0.43" targetFramework="net48" />
  <package id="Serenity.Services" version="3.9.14" targetFramework="net47" />
  <package id="Serenity.Web" version="3.9.14" targetFramework="net47" />
  <package id="Serenity.Web.Assets" version="3.9.2" targetFramework="net47" />
  <package id="Serenity.Web.Tooling" version="3.9.10" targetFramework="net47" />

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Browser Version 91.0.4472.124

**Additional context**
Worked before update to 5

**Comment by dfaruque** [comment]
Try MaxValue = "00"

**Comment by leahmayschneider** [comment]
That worked. Do you know why the fix worked and why the problem happened?

**Comment by MagDev175** [comment]
MaxValue = "00" still doesn't work

**Comment by VictorTomaili** [comment]
Fixed 
https://www.nuget.org/packages/Serenity.Scripts/5.0.44
