### ISSUE TITLE
Hello, I want to ask, where can I change the layout of the invoice in serenity like in the example?

### ISSUE THREAD

**Issue by ahmadfauzanarif** [serenity-is/Serenity#5865]
where can I change the layout of the invoice in serenity like in the example?
![masalah](https://user-images.githubusercontent.com/71299117/125794556-999e8dc5-bd64-4061-badc-9bb1955b870b.png)

to this

![photo_2021-07-15_15-43-36](https://user-images.githubusercontent.com/71299117/125794729-9a751e20-35d7-4d14-826d-97ba3f3a8fcf.jpg)

**Comment by VictorTomaili** [comment]
Please use discussions for questions.
