### ISSUE TITLE
Serene 5.0.41.0+ template

### ISSUE THREAD

**Issue by ArsenioInojosa** [serenity-is/Serenity#5880]
Hello everybody.

How can I create a project with the latest version of the template (5.0.41)?

I have uninstalled and reinstalled the template and it reaches version 5.0.24.0

**This is a problem because the extension must create the template with the latest version available.**

sergen.json
{ "RootNamespace": "Serene1", "ServerTypings": { "LocalTexts": true }, "UpgradeInfo": { "InitialType": "Community", "InitialVersion": "5.0.24.0" } }

https://serenity.is/docs/migration/v5-0-26-to-v5-0-41

![image](https://user-images.githubusercontent.com/11929923/126838030-b742f6a1-d5e4-48e2-bbbf-ad6bdeabb3cb.png)

**Comment by VictorTomaili** [comment]
The latest version of the serene template is 5.0.24.0 
You can manually update NuGet packages for the update to 5.0.41
Next version for the serene template soon.
