### ISSUE TITLE
Telerik Report

### ISSUE THREAD

**Issue by AhmedAbdellah93** [serenity-is/Serenity#5890]
i need telerik reporting with serenity core example 
it not work successfully ?

**Comment by VictorTomaili** [comment]
please use discussions for questions

**Comment by AhmedAbdellah93** [comment]
![Capture](https://user-images.githubusercontent.com/35680735/127487226-facb8752-a9fc-48f0-8f8a-6e263e85fcb7.PNG)

**Comment by AhmedAbdellah93** [comment]
is  telerik report work  well  in serenity .net 5  ?

**Comment by VictorTomaili** [comment]
@AhmedAbdellah93 please use discussions for questions. I lock this issue because it's not a serenity related issue.
