### ISSUE TITLE
Actor/Actrees Show int 0 on CastList - MovieForm

### ISSUE THREAD

**Issue by ahmadfauzanarif** [serenity-is/Serenity#5993]
Hello, I want to ask.  I followed the MovieDatabase tutorial and experienced an error in The cast and characters they played, here I use DBMS Mysql. Why column actor/actrees displays the number 0. Is there a solution?

![image](https://user-images.githubusercontent.com/71299117/134445439-1b2f8732-286e-4d89-b656-6c1dbece20e3.png)

**Comment by VictorTomaili** [comment]
Please use [discussions](https://github.com/serenity-is/Serenity/discussions) for this type of question. Issues are just for the bug reports. Thank you for understanding.
