### ISSUE TITLE
getPersistanceFlags() not being recognized

### ISSUE THREAD

**Issue by ckrassas** [serenity-is/Serenity#6073]
getPersistanceFlags() is not working. I have tried everything in the guide. I seem to be seeing this issue in the current version. I am persisting settings to the database. When using either of the two methods mentioned (one in the guide and the one in this post) it just keeps persisting no matter what.

Any help on this would be greatly appreciated.

Using Serenity Version 3.14

Looks like it might be a mistake in the guide... I've never tried to override the persisted settings but I see that you can do it in your grid.ts like this:

```ts
protected gridPersistanceFlags() {
    return {
        columnWidths: false,
        filterItems: false,
        quickFilters: false
        // etc
    }
}
```

_Originally posted by @edwardch in https://github.com/serenity-is/Serenity/issues/4386#issuecomment-481316482_

**Comment by VictorTomaili** [comment]
Firstly, please use issue template when creating new issue and fill all required fields. When I checked the `gridPersistanceFlags` I didn't found any issue. Current version is 5.1.1 and you mention the version 3.14 (without minor version)
I close this issue, if you had a problem with persisting settings, try to use discussion instead.
