### ISSUE TITLE
404 not found for demo source code

### ISSUE THREAD

**Issue by rchawla-alphabyte** [serenity-is/Serenity#6090]
**Describe the bug**
The code links in the Serenity demo are dead.

**To Reproduce**
1. Ex. Go to https://github.com/serenity-is/Serene/blob/master/Serene/Serene.Core/Modules/BasicSamples/Dialogs/ReadOnlyDialog/ReadOnlyDialog.ts
2. You will see 404 not found

**Expected behavior**
-GitHub link to source code

**Screenshots**
![image](https://user-images.githubusercontent.com/76563021/142007390-ab17fce3-46bd-4392-a261-9357764e4ff6.png)

**Comment by ibrahimGit123** [comment]
Hi- is there an update on this?

Having quick access to these source files is very useful and speeds up development, instead of having to open up a Serenity Project in Visual Studio and check the source file there.

**Comment by imovelsoft** [comment]
https://github.com/serenity-is/Serene/tree/dotnetcore/Serene/Serene.AspNetCore/Modules/BasicSamples/Dialogs

**Comment by ibrahimGit123** [comment]
I am not looking for just one page. All the pages in the demo are down and need to be fixed.

**Comment by VictorTomaili** [comment]
We know, this is why the "todo" tag is added to this issue. You can reach them via repository until fix.

**Comment by ibrahimGit123** [comment]
Alright, thank you

**Comment by volkanceylan** [comment]
This should be mostly fixed in latest release
