### ISSUE TITLE
[Bug] Progress bar/indicator doesn't stop spinning

### ISSUE THREAD

**Issue by hannesb** [serenity-is/Serenity#6093]
**PLEASE ENSURE ABOUT ALL FIELDS FILLED**

- [x] This isn't a feature request or a discussion topic
- [x] I have searched open and closed issues for duplicates
- [x] I am searched documents on https://serenity.is/docs/
- [x] I have read https://serenity.is/docs/startsharp/faq
- [x] I have to use descriptive issue title
- [x] I approve to fill in the information below
 
**Describe the bug**
The progress bar/indicator (pace.js) doesn't stop spinning after loading a page. This is true for all pages including the login page.

**To Reproduce**
1. Create new project with current serene template 
2. Run project

**Expected behavior**
No progress indicator visible or only for a short time

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/1980317/142191967-91b03cb6-f810-4c34-a5be-199143f26fe7.PNG)

**Serenity Versions
 - Serene Template 5.0.51.8 (9.10.2021)
 - Installed Serenity Nuget Packages Versions (you can find them in csproj)
   <ItemGroup>
    <PackageReference Include="Serenity.Assets" Version="5.0.44" />
    <PackageReference Include="Serenity.Scripts" Version="5.0.51" />
    <PackageReference Include="Serenity.Net.Web" Version="5.0.51" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serenity.Extensions" Version="5.0.49.1" />
    
    <PackageReference Include="Serenity.Demo.ThemeSamples" Version="5.0.49.1" />
    
    
    <PackageReference Include="Serenity.Demo.Northwind" Version="5.0.49.1" />
    
    
    <PackageReference Include="Serenity.Demo.BasicSamples" Version="5.0.49.1" />
    
  </ItemGroup>

**Development Environment
 - Visual Studio Version: 2022 Comunity

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome 96.0, edge 95.0

**Comment by VictorTomaili** [comment]
It's because browser link. Doesn't affect production.

**Comment by hannesb** [comment]
Ah ok thanks.

See also here: [Stackoverflow: How to disable Browser Link in ASP.NET Core (.NET 6, VS 2022)](https://stackoverflow.com/questions/69952420/how-to-disable-browser-link-in-asp-net-core-net-6-vs-2022)

**Comment by hannesb** [comment]
This change in _LayoutHead.cshtml solves my issue:

<script type="text/javascript">window.paceOptions = { startOnPageLoad: false, ajax: { trackMethods: ['GET', 'POST'], trackWebSockets: false, ignoreURLs: ['browserLinkSignalR'] } };</script>

**Comment by hannesb** [comment]
Created a pull request for Serene
