### ISSUE TITLE
Error Executing Migration Use MySQL

### ISSUE THREAD

**Issue by ahmadfauzanarif** [serenity-is/Serenity#6100]
### Discussed in https://github.com/serenity-is/Serenity/discussions/6099

<div type='discussions-op-text'>

<sup>Originally posted by **ahmadfauzanarif** November 18, 2021</sup>
![1 pertama](https://user-images.githubusercontent.com/71299117/142364795-ebca9423-c713-47db-bdd7-ab8e965fd69b.png)
![1](https://user-images.githubusercontent.com/71299117/142364801-eb066fb0-664d-49c4-b74a-de3621871ebd.png)
![2](https://user-images.githubusercontent.com/71299117/142364804-cd3bc732-b429-4933-b4f3-9019aa0575aa.png)
![3](https://user-images.githubusercontent.com/71299117/142364807-ab59e0b5-6a31-472b-aeb2-c646db44866a.png)
![4](https://user-images.githubusercontent.com/71299117/142364809-71cc7e61-1c62-4dda-82ea-71dc378db82e.png)
![6](https://user-images.githubusercontent.com/71299117/142364811-9e75faa5-010b-48df-a594-d19394547cae.png)
![7](https://user-images.githubusercontent.com/71299117/142364813-c9ce2d85-61cb-43a2-9e17-a41f630111a4.png)

Hello, I am a beginner.
I want to ask, I created a serenity project using the command prompt in a serin way. when done creating project and running start it worked. Then I opened MySerene.Web in visual studio code and it worked.
This is the problem, because serenity uses the default LocalDB database, so I want to change it to MySql. I followed the guidelines in the documentation, starting from installing the mysql.data package, uncommenting the MySql db provider at startup, and configuring appsettings. when I run the project I am surprised that Property migration runs smoothly. but during the migration process I don't know why the migration stopped when creating the territories table, I waited a long time and finally got an error.
that is the problem
is there a solution?(need fast)</div>

**Comment by VictorTomaili** [comment]
Continue in the discussion. It's a connection problem, not a serenity bug. Read the red text on your screenshots.

**Comment by ahmadfauzanarif** [comment]
I've tried it many times and the problem is like that, I have a friend he also uses mysql and he can when connected to migration.
