### ISSUE TITLE
Mobile phone mode cannot be recognized when opening dialog mode.

### ISSUE THREAD

**Issue by newyearsoft** [serenity-is/Serenity#6106]
**Describe the bug**
Mobile phone mode cannot be recognized when opening dialog mode.

**Screenshots**
![QQ截图20211120111935](https://user-images.githubusercontent.com/20983211/142713162-0d6de503-0fd4-4548-8614-38245b3ea18c.jpg)
![QQ截图20211120112452](https://user-images.githubusercontent.com/20983211/142713173-a07cf58e-1d46-4784-a0c6-60b3651a4cb1.jpg)

**Serenity Versions
 - Latest version

**Comment by newyearsoft** [comment]
![QQ截图20211120114608](https://user-images.githubusercontent.com/20983211/142713423-fb7680c3-a543-4c47-a4f7-890202fca889.jpg)

**Comment by volkanceylan** [comment]
This should be fixed.
