### ISSUE TITLE
Can't find class "SchemaChangeSource" in DataAuditLogHandler , DataAuditLog .net core

### ISSUE THREAD

**Issue by waleed51** [serenity-is/Serenity#6129]
I try to create an audit log in .net core application, "SchemaChangeSource" class can not be found in his namespace "Serenity.Data"  

![image](https://user-images.githubusercontent.com/18492471/144818468-fa70a4db-18cd-44c4-a110-e17526afcecb.png)

![image](https://user-images.githubusercontent.com/18492471/144819968-099c7fc8-c61f-48de-a16f-02b43d3fdccb.png)

please help with that !!

**Comment by VictorTomaili** [comment]
It's removed. You can find it in source history.  Please use discussion for this type of question.
