### ISSUE TITLE
Pro Theme/BS5: Better design / context colored titles for alert dialogs

### ISSUE THREAD

**Issue by volkanceylan** [serenity-is/Serenity#6183]
![image](https://user-images.githubusercontent.com/752470/148568340-68a14564-69b1-485e-97fb-186421c12b55.png)

**Comment by volkanceylan** [comment]
Sweet alert / tablr like design?:
![image](https://user-images.githubusercontent.com/752470/148655946-cd6b9c32-426f-4c7e-be99-0c8288de6846.png)

**Comment by furkanevran** [comment]
I think tabler looks better than sweet alert.
