### ISSUE TITLE
Pro Theme/BS5: Consider offering a classic layout option (similar to old AdminLTE theme)

### ISSUE THREAD

**Issue by volkanceylan** [serenity-is/Serenity#6210]
It might be enabled via a CSS class on HTML element or similar.

The header and sidebar should look similar to old AdminLTE theme layoutwise. E.g. login etc. options on header instead of sidebar band. Back button on panel dialog leftside, instead of right side etc.

**Comment by volkanceylan** [comment]
classic layout option which kinda looks similar to old adminlte theme, you'll need to add s-classic-layout class to html element and remove NavigationGroup definitions in NavigationItems.cs like Administration except the main one (e.g. StartSharp)

**Comment by kilroyFR** [comment]
Any chance you can show us in the code an example on where to add this 's-classic-layout' ? 
Do we have to rebuild Pro-Theme assembly ? Thanks !
