### ISSUE TITLE
Pro Theme/BS5: Group row styling plus/minus

### ISSUE THREAD

**Issue by furkanevran** [serenity-is/Serenity#6214]
![image](https://user-images.githubusercontent.com/14177182/148955914-9ee0a054-37f0-4ea1-838c-7f4a540588fd.png)

| - | + |
|---|---|

buttons does not stick to the right part of the viewport when that div gets scrolled horizontally.

**Comment by volkanceylan** [comment]
Fixed 8c0133497715d0b1aa542163793336c05c5a57a8
