### ISSUE TITLE
SQLite error post update to 5.2 from 5.1

### ISSUE THREAD

**Issue by vinaykulkarni89** [serenity-is/Serenity#6228]
When updated from 5.1 to 5.2 getting following error for SQLite. Getting error while performing new insert operation.

![image](https://user-images.githubusercontent.com/17939331/150290539-0d0bc703-d1c5-453b-9ab6-aaca34f55214.png)

When reverted back to 5.1 works fine

**Comment by VictorTomaili** [comment]
Can you provide these details?
SQLite version
Debug text of insert command

**Comment by VictorTomaili** [comment]
We checked the SQLite functionality with the northwind and default database, There is no issue with save or anything else. Also, there are no major changes in SQLite that will be causing this error. It seems working as expected. 

I close this. If you still have an issue, you can continue with the discussions. After discussion, if there is something related to the Serenity, you can open a new issue about that.
