### ISSUE TITLE
How to set scale for a decimal editor dynamically 

### ISSUE THREAD

**Issue by rahooftkh** [serenity-is/Serenity#6241]
hi
i want to set scale for a decimal editor dynamically from my Dialog
,how to set this ,any idea??

**Comment by VictorTomaili** [comment]
Use [discussions](https://github.com/serenity-is/Serenity/discussions)
Thank you.

**Comment by rahooftkh** [comment]
already posted but no replays

**Comment by VictorTomaili** [comment]
Wait for answers. Issues are for bugs. Community support continues on the Discussions tab.
