### ISSUE TITLE
Cannot join table from another database

### ISSUE THREAD

**Issue by lechu90ns** [serenity-is/Serenity#6271]
Hey Guys!

My client has 2 separate DB, the main already existed when I created a Serenity instance. On the main DB, we have a table with companies (so it is not related to Serenity) but on Serenity, I am creating views/tables with reports where a company name is displayed (via its ID). However, when I am trying to work on listing/dialogs and making assembly annotation (on Row layer, on Serenity end) to join an object that is connected to a Company table (from the second DB) I've got issues that table does not exist. I noticed that code-behind listing handlers do not open a separate connection when a different DB is set on a join.

I don't want to change the table schema itself to just display the name and pass it through SQL, because I need to create links on the Serenity and we need to save storage due to the high amount of data.

Any ideas?

Thanks

**Comment by VictorTomaili** [comment]
For questions, please use [discussions](https://github.com/serenity-is/Serenity/discussions)

**Comment by lechu90ns** [comment]
I would say that is a bug

**Comment by VictorTomaili** [comment]
It's not a bug. Serenity doesn't have this type of join & connection support. If you want to add, PR's are wellcome. If you need a solution for this, use discussion for community support.
