### ISSUE TITLE
Migrate to .NET 6 (.NET 5 and Visual Studio 2019 support will be dropped)

### ISSUE THREAD

**Issue by volkanceylan** [serenity-is/Serenity#6337]
.NET 5 is a "current" version e.g. not a "LTS (Long Term Support)" version and Microsoft will officially drop support after May 8, 2022:

https://dotnet.microsoft.com/en-us/platform/support/policy

We are moving Serene / StartSharp and Serenity.Net.Web to .NET 6 and dropping support for .NET 5 as well. So the last Serenity version based on .NET 5 will probably be 5.2.4.

As .NET 6 is not supported in Visual Studio 2019, this also means you need to use Visual Studio 2022.

## Migrating to .NET 6:

Just update all Serenity packages as usual to 6.0.0.

Change target framework to `net6.0` in YourProject.csproj:

```xml
<TargetFramework>net6.0</TargetFramework>
```

Also update these references as shown:

```xml
    <PackageReference Include="EPPlus" Version="4.5.3.3" />
    <PackageReference Include="FluentMigrator.Runner" Version="3.3.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="6.0.3" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="4.6.2">
```

Replace:

```cs
using var md5 = new MD5CryptoServiceProvider();
```

with 

```cs
using var md5 = MD5.Create(); 
```

This should do it.

We'll be adding a migration guide to https://serenity.is/docs and stargen upgrade next week.

**Comment by ibrahimGit123** [comment]
I do not see a migration guide yet at https://serenity.is/docs. When do you expect this will be ready?

**Comment by gsaielli** [comment]
Any news about the guide? The simple instructions at the top are not enough... Any sleekgrid is blank, after upgrading, throughout the entire application.

Thank you.

**Comment by VictorTomaili** [comment]
Nothing too much complicated on this upgrade. The document is updated but not published yet. 
https://github.com/serenity-is/docs/blob/master/migration/v5-2-3-to-v6-0-0.md

**Comment by nahidulislam-cse15** [comment]
i installed latest serene template in vs -2022 .when creating new project  this error happens "dotnet sergen servertypings" exit code 1.how to resolve this ?
