### ISSUE TITLE
Interface background error when running demo tutorial.

### ISSUE THREAD

**Issue by roki1031** [serenity-is/Serenity#6348]
**PLEASE ENSURE ABOUT ALL FIELDS FILLED**

- [√ ] This isn't a feature request or a discussion topic
- [ √] I have searched open and closed issues for duplicates
- [ √] I am searched documents on https://serenity.is/docs/
- [ √] I have read https://serenity.is/docs/startsharp/faq
- [ √] I have to use descriptive issue title
- [ √] I approve to fill in the information below
 
**Describe the bug**
When operating the tutorials provided by serenity, the login interface does not display the background image. When entering the order page, the error icon is displayed.

**To Reproduce**
1. Download the serenity template from vs2022.
2. Run project
3.  you will see this picture 
![image](https://user-images.githubusercontent.com/52522880/161271825-e3de2dd5-0ddd-45e7-8246-656b0c1264ad.png)
4. After successful login, we click the "order" menu, and we will see ...
![image](https://user-images.githubusercontent.com/52522880/161272010-5fea77f7-60ce-4ca4-84df-e8bfa947fc10.png)
![image](https://user-images.githubusercontent.com/52522880/161272030-258b4e97-c60e-4d6d-9588-3abe7c87ca65.png)
![image](https://user-images.githubusercontent.com/52522880/161272072-fe459189-4651-4bcb-b04c-46c7c270dc98.png)

**Serenity Versions
 - Serene Template Version ：5.2.4.0

**Development Environment
 - Visual Studio Version:2022
 - Nodejs Version:
 - Typescript Version:
 - Database:
 - Database Version:

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Additional context**

**Comment by VictorTomaili** [comment]
try to run `dotnet sergen restore` Your css is not loaded correctly.

**Comment by roki1031** [comment]
`dotnet sergen restore` It doesn't work.
![image](https://user-images.githubusercontent.com/52522880/161363744-7cd84ba1-ffe5-419e-bc9d-aa973971d543.png)

**Comment by KursatKonak** [comment]
I am having the same problem. I installed latest VS Extension, created a Serene template, did F5 got same error (HTTP 4040 Content/Serenity/serenity.css is missing) . Then did dotnet sergen restore didn't work (runs successfully with no text output / nothing is added to wwwroot). Tried serin to generate via console which basically downloads vsix and executes so problem persists.

**Comment by roki1031** [comment]
@VictorTomaili  Hello, I think the root cause of this error may be because of `Error while initializing MSBuildLocator: System.InvalidOperationException: No instances of MSBuild could be detected.
Try calling RegisterInstance or RegisterMSBuildPath to manually register one..` 
Do you have a better solution?

**Comment by dfaruque** [comment]
which visual studio version you have? try visual studio 2022

**Comment by roki1031** [comment]
> which visual studio version you have? try visual studio 2022

Yes, I use visual studio 2022  and the version of .net is 6.0.0

**Comment by roki1031** [comment]
> which visual studio version you have? try visual studio 2022

To reproduce this error, you can try to download a serenity new template in vs 2022 and run from scratch.

**Comment by VictorTomaili** [comment]
@roki1031 @KursatKonak check this 
https://github.com/serenity-is/Serenity/discussions/6307#discussioncomment-2314463=
