### ISSUE TITLE
Child deleted records is not shown when IIsActiveDeletedRow is implemented while used in a MasterDetailRelation

### ISSUE THREAD

**Issue by wirble** [serenity-is/Serenity#6376]
Currently, all my tables implements IIsActiveDeletedRow so in the grid.ts file I added:
`protected getIsActiveProperty() { return xxxxRow.isActiveProperty; }`

When clicking on this in the regular grid, the deleted item shows up.  However, I am unable to get deleted items to show up for the child table when used in a MasterDetailRelation.  Even after I added same code in the xxxEditor.ts file.

Has anyone successfully gotten the deleted child items to show up?  Wondering if this is a bug of the MasterDetailRelation...

It seems like the child's data only gets called once when the parent table is opened.  Clicking on the show deleted button doesn't trigger another call to the childs' repository.  If I override ApplyIncludeDeletedFilter in the MyListHandler, then I am able to get all of the records to show, but the questions is how to trigger the call when the show deleted button is pressed.

**To Reproduce**
1. Implementing IIsActiveDeletedRow on a parent and child table.  
2. Create MasterDetailRelation
3. Add one parent record.
4. Add two child records
5. Delete one child record.
6. Click on "display inactive record" on child relation within the parent record.
7. Deleted record does not show.  There is no call to the child list handler or no requerying.

**Expected behavior**
It should requery the child table with IncludeDeleted set to true and display deleted record within the child masterdetailrelation

**This shows there is a deleted record**
![delete1](https://user-images.githubusercontent.com/8212422/164725441-259c07cc-f271-41ae-acfc-22d0536c821d.gif)

**Deleted record not shown when in MasterDetailRelation**
![delete2](https://user-images.githubusercontent.com/8212422/164725437-17038845-1362-469a-88cb-d8c3abb32b7c.gif)

_Originally posted by @wirble in https://github.com/serenity-is/Serenity/discussions/6375_

**Comment by VictorTomaili** [comment]
use [discussions](https://github.com/serenity-is/Serenity/discussions) instead issues. and deleted records in the child grid is uses the behavior implementation. 
https://github.com/serenity-is/Serenity/blob/master/src/Serenity.Net.Services/RequestHandlers/IntegratedFeatures/MasterDetail/MasterDetailRelationBehavior.cs#L114
