### ISSUE TITLE
Removing LESS Generation

### ISSUE THREAD

**Issue by recozo** [serenity-is/Serenity#6377]
**PLEASE ENSURE ABOUT ALL FIELDS FILLED**

- [x] This isn't a feature request or a discussion topic
- [x] I have searched open and closed issues for duplicates
- [x] I am searched documents on https://serenity.is/docs/
- [x] I have read https://serenity.is/docs/startsharp/faq
- [x] I have to use descriptive issue title
- [x] I approve to fill in the information below
 
**Describe the bug**

I follow the tutorial: Movie Database,  how can I customizing dialog height to 500px (in desktop mode), the project has removed less generation, but the tutorial still use it.

why remove less generation?  how define theme  now ?

thanks

**Comment by VictorTomaili** [comment]
You can use css directly instead compile less. You can see the variables for the theme. We just removed the one step from build to improve build speed and for "less complicated" CSS modifications. 
Use discussions instead open this type of issue. Issues are for bugs only.
