### ISSUE TITLE
Incorrectly displayed styles.

### ISSUE THREAD

**Issue by DuckMcQu4ck** [serenity-is/Serenity#6396]
Incorrectly displayed styles. All packages updated to latest version, using .NET 6. Tried different browsers, different devices.
![image](https://user-images.githubusercontent.com/59172095/168456811-bee47ad3-c2bd-4cf4-87a2-a6aa1737d8de.png)
![image](https://user-images.githubusercontent.com/59172095/168456827-39abc4cd-47bf-41c8-a7ef-f4c2874bafcb.png)
![image](https://user-images.githubusercontent.com/59172095/168456854-67640375-b255-4432-8b13-d96741c5fd68.png)

**Comment by VictorTomaili** [comment]
Please use [discussions](https://github.com/serenity-is/Serenity/discussions).
Your issue probably related to the static contents. They are not restored properly. 
https://github.com/serenity-is/Serenity/blob/523c0195fec17089e1dd7e812650c2edaf47a7ac/INSTALL.md#:~:text=tool%20update%20sergen-,dotnet%20sergen%20restore,-so%20that%20static
