### ISSUE TITLE
How to Add RDLC or SSRS Report in Serenity Framework ?

### ISSUE THREAD

**Issue by Pujianto0** [serenity-is/Serenity#6397]

**Comment by VictorTomaili** [comment]
use [discussions](https://github.com/serenity-is/Serenity/discussions)

**Comment by stixoffire** [comment]
@Pujianto0 I did this, a bit crude but it worked. I would write it better but hadn't had time. Send me a message to send you the code. I want to modify it to better structure of code. Header, Body,Footer.
