### ISSUE TITLE
File Upload Editor

### ISSUE THREAD

**Issue by NivethaTechStarz** [serenity-is/Serenity#6442]
### Discussed in https://github.com/serenity-is/Serenity/discussions/6432

<div type='discussions-op-text'>

<sup>Originally posted by **NivethaTechStarz** June 29, 2022</sup>
Hi,
Customized the upload editor and set DisableDefaultBehavior set to true, So that It is not use the Image upload behaviour , then how can it save in database as json format
Thanks for any reply in advance</div>

**Comment by VictorTomaili** [comment]
Issues for bug reports. Please dont use issues to ask questions. You should create own behavior to save it in this case.
