### ISSUE TITLE
SelectableEntityGrid Sample not working after update to 6.0.3

### ISSUE THREAD

**Issue by RaptorTrap** [serenity-is/Serenity#6445]
**PLEASE ENSURE ABOUT ALL FIELDS FILLED**

- [x] This isn't a feature request or a discussion topic
- [x] I have searched open and closed issues for duplicates
- [x] I am searched documents on https://serenity.is/docs/
- [x] I have read https://serenity.is/docs/startsharp/faq
- [x] I have to use descriptive issue title
- [x] I approve to fill in the information below
 
**Describe the bug**
After updating the Serenity Nuget Packages to version 6.0.3 in an existing project the highlight selected Row (see Demo 'Enabling Row Selection', SelectableEntityGrid) is not working anymore, instead the following error comes up in DevTools:
> Uncaught TypeError: Cannot read properties of undefined (reading 'className')

**To Reproduce**
1. Update Serenity packages to 6.0.3
2. Add code to a grid from Sample 'Enabling Row Selection'
3. Try to select a row on the grid

**Expected behavior**
No error should come up and the selected row should be highlighted

**Screenshots**
![image](https://user-images.githubusercontent.com/49608875/177124820-a8ab07ff-3d12-482b-afed-a94e8b996b81.png)

**Serenity Versions**
 - Installed Serenity Nuget Packages Versions: 6.0.3

**Comment by VictorTomaili** [comment]
Update assets package `Install-Package Serenity.Assets -Version 6.0.4` 
In serene, you may not have background color for `slick-row-selected` class. You can modify it as you wish.

**Comment by RaptorTrap** [comment]
Thank you, the update fixed the issue.
