### ISSUE TITLE
[Bug report]: <SqlException: Invalid object name 'Languages'>

### ISSUE THREAD

**Issue by moseur** [serenity-is/Serenity#6506]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I am searched documents on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have do a search in the discussion and old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

Hello All Specialist,

Respect to all. I am facing a problem, When I going to change the dbname like something like this => Database=ABCERP, Then its showing en error like "SqlException: Invalid object name 'Languages" , But If I check to local db , then I found the Db with same name I have provided in connection string but without any table. Could you please help me to figure it out.

Thanks & Best regards
Moseur

### What did you expect to happen?

Please help me t solve it out

### How to reporoduce?

Just help me to figure it out

### Sergen version

Serenity.Net.Web" Version="5.0.51

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

Serenity.Scripts" Version="5.0.51

### Operating System

Windows 10

### Node.js version

v16.13.2

### Database type and version

Sql Server 2019

### What device are you seeing the problem on?

Laptop

### What operating system are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Additional information

I have searched at google and serenity docs , may be I am not so much smart.

**Comment by VictorTomaili** [comment]
Please ask in discussion section. Your migrations are not running on start.
