### ISSUE TITLE
AutowidthMixin disabled property not functioning

### ISSUE THREAD

**Issue by DrastiGohel** [serenity-is/Serenity#6509]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

Hello,

I have added AutoWidthMixin and set it disabled = true. But it is not disabled initially, the column resizes on grid refresh

![image](https://user-images.githubusercontent.com/98172041/185936648-c4cb3291-91b5-425a-abf6-39d15599da16.png)

### What did you expect to happen?

- I wanted it to take sizes from UserPreferences at first until the user himself double clicks the column to auto-resize it.
- If user double clicks column to change width, that new width should be saved to user preferences

Note: I have added Width Attributes to multiple columns

### How to reproduce?

1. Open a grid
2. Resize any column to random width
3. Refresh Page
4. It should come to the width set at step 2
5. Instead it auto resize it

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

Serenity.Pro.Script 3.9.10 (Serenity.Pro.App.d.ts)

### Sergen version

3

**Comment by VictorTomaili** [comment]
`AutoColumnWidthMixin` is a pro helper. Please use StartSharp repository to open issue
