### ISSUE TITLE
Permissions checkboxes not rendering well

### ISSUE THREAD

**Issue by VictorTomaili** [serenity-is/Serenity#6542]
### Discussed in https://github.com/serenity-is/Serenity/discussions/6539

<div type='discussions-op-text'>

<sup>Originally posted by **gfo2007** September 19, 2022</sup>
Hi,
Below is the image of the Permissions dialog box. The checkboxes that allows a user to select permissions are not rendering well in the UI  for them to be ticked by the user.

Am I missing a library or is a library not loading well? 

![permissions rendering](https://user-images.githubusercontent.com/14317420/191059976-be777b80-6f31-4ab2-b76f-5502a75af22b.PNG)
</div>

**Comment by VictorTomaili** [comment]
Use the latest version of sergen. 

`dotnet tool update sergen`

**Comment by gfo2007** [comment]
Thanks @VictorTomaili
