### ISSUE TITLE
WorkLog App: Improve UX / speed for adding an issue

### ISSUE THREAD

**Issue by volkanceylan** [serenity-is/Serenity#6550]
While adding a new work log, show project selection first, then tag and make sure when there is only one project matching the typed text, the project can be selected by just pressing enter, and while entering tags, setting a tag and pressing enter goes to next step. Then the description should be active and issue can be added with another enter. So three enter keys to create a new issue quickly.

**Comment by osmanaslancan** [comment]
Improve UX on Login Page,
Open Tag Editor when clicked on any tag

**Comment by osmanaslancan** [comment]
fix the sum for past works

**Comment by volkanceylan** [comment]
Fixed
