### ISSUE TITLE
Slickgrid plugins update

### ISSUE THREAD

**Issue by VictorTomaili** [serenity-is/Serenity#6553]
`slick.rowselectionmodel.js` gives exception while `slick.setColumns` is called. 

File: ScriptInitialization.ts
Temporary fix 
```typescript
$(function(){
        //TemporaryFix
        Slick.RowSelectionModel.prototype["refreshSelections"] = () => { };
});
```

**Comment by volkanceylan** [comment]
Fixed in latest SleekGrid but we need to update plugins, while checking if they any other breaking change.
