### ISSUE TITLE
No data displaying after .NET 6 upgrade, data still in DB and login works

### ISSUE THREAD

**Issue by Thebenmandude** [serenity-is/Serenity#6558]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

After upgrade my project to .NET 6 and updating all serenity dependencies to 6.+ I am able to log in but none of my data is showing, no users, languages, roles, custom views, nothing. 
My data however is still in my database
![image](https://user-images.githubusercontent.com/6910368/195440211-b62feea1-40c2-4a0c-8a2f-ea3800945cea.png)
![image](https://user-images.githubusercontent.com/6910368/195440330-4175b327-f755-4a49-a915-af33bc84c9b5.png)

### What did you expect to happen?

After the upgrade, I expected my data to be visible

### How to reproduce?

I am not sure how to reproduce this

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

6.2.1

### Code editor

Visual Studio 2022

### Operating System

Windows 11

### Database type and version

Azure SQL

### On which device do you see the problem?

Desktop

### On which operating system do you see the problem?

Windows

### On which browsers do you see the problem?

Microsoft Edge

**Comment by VictorTomaili** [comment]
Update to latest serenity scripts nuget package.
