### ISSUE TITLE
Subtotals are not appearing in Customizable Summaries with Grouping

### ISSUE THREAD

**Issue by ibrahimGit123** [serenity-is/Serenity#6577]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

In the latest version of Serenity, Subtotals for each Group no longer appear with Customizable Summaries with Grouping

Subtotals would go where the red line is in the image below:
![image](https://user-images.githubusercontent.com/57414714/201453271-244c564c-a2e8-4a51-afa8-2c47369c21df.png)

In previous Serenity Versions there were Subtotals.

### What did you expect to happen?

There should be Subtotals for each Group

### How to reproduce?

Create a Grid with Customizable Summaries and Drag and Drop Grouping. Group by a column and there will be no subtotals for each Group

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

6.2.6

### Code editor

VS 2022

### Operating System

Windows 10

### Database type and version

SQL Server

### On which device do you see the problem?

Desktop

### On which operating system do you see the problem?

Windows

### On which browsers do you see the problem?

Chrome

**Comment by VictorTomaili** [comment]
fixed in 6.3.2 version. Update Serenity.Scripts and Serenity.Assets

**Comment by ibrahimGit123** [comment]
Thanks for that. We are currently on Serenity version 6.2.6. Will moving to version 6.3.2 cause any breaks in our code?

**Comment by VictorTomaili** [comment]
Check the changelog for any breaking change
https://github.com/serenity-is/Serenity/blob/master/CHANGELOG.md

**Comment by ibrahimGit123** [comment]
It seems this is not working again. See https://demo.serenity.is/AdvancedSamples/CustomizableSummaries

**Comment by VictorTomaili** [comment]
Let me check it again
