### ISSUE TITLE
Demo Module Northwind reports currently broken on line

### ISSUE THREAD

**Issue by LSNicholls** [serenity-is/Serenity#6583]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

You probably already know this but the demo page https://serenity.is/demo/Northwind/Reports# is down.  I tried multiple browsers, just in case.  It happens on all three sample reports

![image](https://user-images.githubusercontent.com/88156108/202587964-48c87188-1869-4cdf-bf5b-d3c828edf6ff.png)

### What did you expect to happen?

I expected to see reports <g>.

### How to reproduce?

Go to the page and click on any of the three Report links.

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

This is the on line demo, so no idea.

### Additional information

Tried desktop only.

**Comment by volkanceylan** [comment]
This is fixed in latest demo / common-features Serenity.Extensions package

**Comment by LSNicholls** [comment]
Thank you!
