### ISSUE TITLE
[Bug report]: <Short description of the bug>

### ISSUE THREAD

**Issue by ArsenioInojosa** [serenity-is/Serenity#6594]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

It is not displayed correctly.

![image](https://user-images.githubusercontent.com/11929923/203844260-42050b0a-2e39-4f47-bdd2-08ee0d6e86ff.png)

### What did you expect to happen?

You need to generate and upload the serenity.css file

### How to reproduce?

Create a new project and run.

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

Serenity.Assets.6.3.6, Serenity.Scripts.6.3.6, Serenity.Extensions.6.3.6, Serenity.Net.Web.6.3.6

### Serene template version

6.3.6

### Sergen version

6.3.6.0

### Code editor

Visual Studio 2022

### Operating System

Windows 11

### Node.js version

v16.18.0

### TypeScript version

4.7.4

### Database type and version

SQL Server 2019

### On which device do you see the problem?

Desktop

### On which operating system do you see the problem?

Windows

### On which browsers do you see the problem?

Chrome

**Comment by volkanceylan** [comment]
Newly created project:

<img width="245" alt="image" src="https://user-images.githubusercontent.com/752470/204056032-ae3c9e57-a96a-44af-b198-09b5a603070c.png">

Open a command prompt and run `dotnet sergen restore`

The template normally runs this and build on project creation. Your environment must have something wrong.
