### ISSUE TITLE
[RTL in Mobile View]: <GridDiv removes Columnts >

### ISSUE THREAD

**Issue by ageeb1982** [serenity-is/Serenity#6595]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

In GridDiv table when I change direction to RTL and select mobile mode

The page removes the columns from the left side of the table 

 

[https://serenity.is/demo/Northwind/Customer](https://serenity.is/demo/Northwind/Customer)

look at the Video
https://user-images.githubusercontent.com/17899024/204125534-8a64663a-9901-42b8-906f-3bc38a2fbc3e.mp4

### What did you expect to happen?

fix it

### How to reproduce?

-

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

6.0.8

### Code editor

Visual Studio Code V1.73.1

### Operating System

Ubuntu 20.04 LTS

### Node.js version

v10.24.1

### TypeScript version

6.14.4

### Database type and version

Sqlserver 2019

### On which device do you see the problem?

Laptop

### On which operating system do you see the problem?

Linux 

### On which browsers do you see the problem?

Chrome

**Comment by volkanceylan** [comment]
This is fixed in latest version.
