### ISSUE TITLE
ERROR ON SERGEN

### ISSUE THREAD

**Issue by fahmiyonda007** [serenity-is/Serenity#6616]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

there is a problem when we want to generate, an exclamation mark appears in the checkbox and does not display an error. button generate is disable.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/28822275/208019996-02515391-c7b6-41b7-a3c2-7762c0634227.png">

### What did you expect to happen?

I hope this problem can be resolved and get a good solution so that the Sergen GUI can run normally again

### How to reproduce?

I hope this problem can be resolved and get a good solution so that the Sergen GUI can run normally again

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

Serenity.CodeGenerator 3.7.7, Serenity.Core 3.7.7, Serenity.Data 3.7.7, Serenity.Data.Entity 3.7.7, Serenity.Services 3.7.7, Serenity.Web 3.7.7, Serenity.Web.Assets 3.7.7, Serenity.Web.Tooling 3.5.1

### Sergen version

Serenity.CodeGenerator 3.7.7

### Code editor

Microsoft Visual Studio Community 2019 Version 16.11.18

### Operating System

Windows 11

### Node.js version

16.18.0.

### TypeScript version

3.1

### Database type and version

SQL Server, 18.12.1

**Comment by volkanceylan** [comment]
Use discussions, this is a very old sergen version, no longer supported
