### ISSUE TITLE
[Bug report]: PasswordConfirm validation

### ISSUE THREAD

**Issue by marcobisio** [serenity-is/Serenity#6648]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

PasswordConfirm "addValidationRule" event isn't triggered when updating an user if the field itself is empty. If the Password field has a value, then the password is properly updated but without checking the PasswordConfirm field.

### What did you expect to happen?

PasswordConfirm field should be always validated if the Password field has a value

### How to reproduce?

Just updating a user in the demo site

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

6.4.4

**Comment by VictorTomaili** [comment]
Fixed
