### ISSUE TITLE
id parameter in call to validateEntity from GridEditorBase is set to null even though an existing item in the grid was selected

### ISSUE THREAD

**Issue by DGoertzen** [serenity-is/Serenity#6668]
### What happened?

After editing an item in a "detail list" created by using GridEditorBase (similar to the Order detail at https://demo.serenity.is/Northwind/Order#edit/11077 ) , validateEntity is called with id == null.  This causes an additional item to be put into the detail list, rather than replacing the item that was edited.  After debugging, I found that the function save in GridEditorBase calls:

`        var id = this.id(row);`

id is returned as null, even though this is a row that is being edited, not created.  Here is a screen shot of from visual studio showing that, after executing that call above, row is valid, but id is not defined

![image](https://user-images.githubusercontent.com/22012694/214477355-e757bc07-5b78-4be7-bcbb-6389a5d2490e.png)

I checked the html and it looks fine.

![image](https://user-images.githubusercontent.com/22012694/214477791-865b7908-d5df-49c7-bffe-7957f266f946.png)

### What did you expect to happen?

I expected that, when the function validateEntity is called, that id would be set to a valid number rather than null when a existing item is selected in a detail list.

### How to reproduce?

The behavior seems to be consistent for all detail list editors that I have implemented.  I did not think it had this behavior in the past and am wondering if it is do to a more recent Serenity release, or I've screwed something up in my development environment, or I've done something stupid...  

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

6.4.10

### Operating System

Windows 11

**Comment by volkanceylan** [comment]
I don't see this in Order Details editor, so probably you have something different in your editor.

**Comment by volkanceylan** [comment]
Check if you have a getIdProperty() method in your grid editor. You should not have that.

**Comment by DGoertzen** [comment]
You are a genius.  Thanks.  I did have a getIdProperty() in the GridEditorDialog class.  Removing that fixed the problem. Now that I knew what to look for, I even found that you had troubleshooting on it already - https://github.com/serenity-is/docs/blob/a89a776a0136966926bbc5df3176d4c4dad86cc7/faq/troubleshooting.md#masterdetail-editing

Sorry I missed that.  Thanks for your great help!
