### ISSUE TITLE
Serenity obselute extension not working in vs 2022

### ISSUE THREAD

**Issue by Saad2025** [serenity-is/Serenity#6676]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

I'm sorry for making this issue but why you don't make exetension for serenity obselute .net framework in visual studio 2022.
I know that you stopped support on serenity obsulute but at least make it avialable for vs 2022 when creating the project

I know that I can make it work on vs2022 by downloading it from github or by creating it on vs 2019 and then run it on vs 2022 but this way isn't the best way.

please make it in your mind and don't ignore it cause I want to make a new course in arabic language for serenity core and also serenity obsulute and this thing make me not working on it untill now 

thanks alot and again sorry for assigning this issue here I'm waiting for your reply

### What did you expect to happen?

I expect to add extension for creating serene obsulute on vs 2022

### How to reproduce?

I can create videos course for serenity as I did before but this time in more enhanced way

thanks in advance

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

serenity obsulute

**Comment by VictorTomaili** [comment]
Hello @Saad2025 

The obsolete package is end of support. The .net Framework 4.x support is already ended. But there is a new version for .net6 and vs2022. 

Please see link below:
https://marketplace.visualstudio.com/items?itemName=VolkanCeylan.SereneSerenityApplicationTemplate
