### ISSUE TITLE
ServiceLookupEditor - search field not working correctly

### ISSUE THREAD

**Issue by ibrahimGit123** [serenity-is/Serenity#6688]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

When i use ServiceLookupEditor - the search field is not working properly. Note that my code uses Namespaces (not ESM).

![image](https://user-images.githubusercontent.com/57414714/218546780-9900161d-d79d-401f-8412-5b69534f60fd.png)

![image](https://user-images.githubusercontent.com/57414714/218546837-d775450c-c671-4b6d-aea8-9f93b41eba66.png)

In example above, typing 707 does not filter to the proper record. Instead, nothing appears.

### What did you expect to happen?

When I start typing, the search result should show the correct options

### How to reproduce?

Use a lookup field with ServiceLookupEditor where the options have multiple works

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

6.48

### Code editor

VS 2022

### Operating System

Windows 11

### Database type and version

Azure SQL

### On which browsers do you see the problem?

Chrome

**Comment by ibrahimGit123** [comment]
I was able to solve the issue. The Name Field of the lookup editor (which is what shows the search options) needed to be added with the QuickSearch attribute for it to work properly.

**Comment by volkanceylan** [comment]
This is by design, quick search only applies to fields with [QuickSearch] attribute
