### ISSUE TITLE
Subtotals are not appearing in Customizable Summaries with Grouping

### ISSUE THREAD

**Issue by ibrahimGit123** [serenity-is/Serenity#6692]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

 Subtotals for each Group no longer appear with Customizable Summaries with Grouping

Subtotals would go where the red line is in the image below:
![image](https://user-images.githubusercontent.com/57414714/219098817-771003d1-ccf8-4bcc-a6b2-5206f42047c7.png)

The issue appears in the demo https://demo.serenity.is/Account/Login/?ReturnUrl=%2FAdvancedSamples%2FCustomizableSummaries

This is the same issue as https://github.com/serenity-is/Serenity/issues/6577.

### What did you expect to happen?

Subtotals should appear for each grouping

### How to reproduce?

Add Custom Summaries with Grouping

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

6.48

**Comment by VictorTomaili** [comment]
With the next release, this issue will be resolved. Current fix: 

```ts
export class CustomizableSummariesGrid extends EntityGrid<ProductRow, any> {
    protected getColumnsKey() { return ProductColumns.columnsKey; }
    protected getDialogType() { return <any>ProductDialog; }
    protected getIdProperty() { return ProductRow.idProperty; }
    protected getLocalTextPrefix() { return ProductRow.localTextPrefix; }
    protected getService() { return ProductService.baseUrl; }

    private groupItemMetadataProvider: GroupItemMetadataProvider;

    protected createToolbarExtensions() {
        super.createToolbarExtensions();

        this.slickGrid.registerPlugin(this.groupItemMetadataProvider);

        new DraggableGroupingMixin({
            grid: this,
            displayTotalsRow: true
        });

        new CustomSummaryMixin({
            grid: this
        });
    }

    protected getViewOptions() {
        var options = super.getViewOptions();
        this.groupItemMetadataProvider = new GroupItemMetadataProvider();
        options.groupItemMetadataProvider = this.groupItemMetadataProvider;
        return options;
    }

    protected getSlickOptions() {
        var opt = super.getSlickOptions();
        opt.groupingPanel = true;
        opt.showFooterRow = true;
        return opt;
    }
}
```
