### ISSUE TITLE
[Bug report]: Pro-packages are not restored while creating a new project from visual studio

### ISSUE THREAD

**Issue by metharath** [serenity-is/Serenity#6696]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

I recently subscribed to the pro version of serenity. I'm very new to this framework.
I followed your installation guide and installed it in VS2022. I created a sample application through VS using the Startsharp template and decided to have both Northwind and Pro samples. 
The project was created while building the application it gives me the below errors.
 
Error	NU1101	Unable to find package Serenity.Pro.Coder. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	PMS.Web	xxxxxx\PMS.Web.csproj	 	
Error	NU1101	Unable to find package Serenity.Pro.Extensions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	PMS.Web	xxxxxx\PMS.Web.csproj	1	
Error	NU1101	Unable to find package Serenity.Demo.AdvancedSamples. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	PMS.Web	C:\Users\Kadar\source\repos\PMS\PMS\PMS.Web\PMS.Web.csproj	1	

This error shows for all Pro samples (organization, work log, meeting etc.).

Contradictorily, when I checked the package manager, these packages were found installed for this project (ref image)
![image](https://user-images.githubusercontent.com/7655896/219846720-ed9abb66-9a75-44e5-9bc2-cb289db93875.png)

I've tried to create the project using dotnet serin <projname> command, which makes the project also compile without any errors. However, this doesn't include the Pro samples.
Not sure what mistake I make, please advise.

### What did you expect to happen?

After creating the project using the startsharp template, it should compile with out any build error

### How to reproduce?

It may not be able to reproduce at your end

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

serenity pro startsharp

### On which browsers do you see the problem?

Chrome

**Comment by VictorTomaili** [comment]
For pro packages (and StartSharp) related questions and issues, please open issue in StartSharp repository. This repository is related to the serenity base libraries and free version with community support.

Currently, there is no problem exist related pro packages. You need to follow the `nuget` related instructions in members area. Please read carefully the `Serenity Pro Packages` section. You can log in to members area from here, https://serenity.is/
