### ISSUE TITLE
[Bug report]: It getting an Oracle Error When oracle commend has Group by 

### ISSUE THREAD

**Issue by wow-prime** [serenity-is/Serenity#6724]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

If I use GroupBy like below picture.

![image](https://user-images.githubusercontent.com/19904096/224250054-033e1ee2-9716-4f84-bc2c-17e30fc8293c.png)

The Commend  will be generated like below picture.

![image](https://user-images.githubusercontent.com/19904096/224251348-e87c88a6-97f1-4ef4-be7e-1f3bfcceaa61.png)

I get Oracle.ManagedDataAccess.Client.OracleException: 'ORA-00911 error.

First character cannot start with an underscore in Oracle.

I found the code at 
[[                sb.Append(" 1 as _alias_x_ ");](https://github.com/serenity-is/Serenity/blob/f3e0a7a5761860b38d8becd84f37f0dd7217088a/src/Serenity.Net.Data/FluentSql/SqlQuery_ToString.cs#L419)]
and 
https://github.com/serenity-is/Serenity/blob/f3e0a7a5761860b38d8becd84f37f0dd7217088a/src/Serenity.Net.Data/FluentSql/SqlQuery_ToString.cs#L426

### What did you expect to happen?

modify below 
[[                sb.Append(" 1 as _alias_x_ ");](https://github.com/serenity-is/Serenity/blob/f3e0a7a5761860b38d8becd84f37f0dd7217088a/src/Serenity.Net.Data/FluentSql/SqlQuery_ToString.cs#L419)]
and 
https://github.com/serenity-is/Serenity/blob/f3e0a7a5761860b38d8becd84f37f0dd7217088a/src/Serenity.Net.Data/FluentSql/SqlQuery_ToString.cs#L426

### How to reproduce?

modify below 
[[                sb.Append(" 1 as _alias_x_ ");](https://github.com/serenity-is/Serenity/blob/f3e0a7a5761860b38d8becd84f37f0dd7217088a/src/Serenity.Net.Data/FluentSql/SqlQuery_ToString.cs#L419)]
and 
https://github.com/serenity-is/Serenity/blob/f3e0a7a5761860b38d8becd84f37f0dd7217088a/src/Serenity.Net.Data/FluentSql/SqlQuery_ToString.cs#L426

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

Serenity.Net.Data 6.5.4

### Serene template version

6.5.4 5.2.3

### Sergen version

5.2.3

### Code editor

2022

**Comment by VictorTomaili** [comment]
Will be released with the next version. 
f9d6b4b13edaed42313f2d6446bed3cd3d5e29bd
