### ISSUE TITLE
 Error after pacakage and framework update

### ISSUE THREAD

**Issue by vinaykulkarni89** [serenity-is/Serenity#6726]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

I have updated the project from .Net core 5 to .Net Core 7 and accordingly, packages got updated, my project gets compiled properly however when I try to add or update existing data I am getting the following error.

Method not found: 'Void Serenity.Data.Row`1.set_TrackAssignments(Boolean)'.

### What did you expect to happen?

To get new records and existing records get saved and updated

### How to reproduce?

Update the project from .Net core 5 to .Net Core 7 and update packages

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

Serenity.Scripts 5.1.1

**Comment by VictorTomaili** [comment]
We currently support .net 6 LTS and we will continue with .net 8 LTS. But .net 7 should work without any issue if you manually change the framework version. 

Your problem is not related .net 7 version. Check the [Changelog](https://github.com/serenity-is/Serenity/blob/master/CHANGELOG.md#:~:text=build%20%2Dtarget%3ARestoreTypings-,%5BBREAKING%20CHANGE%5D%20Some%20row%20properties%20are%20only%20available%20via%20IRow%20or%20IEditableRow%20interface.,-Introduced%20IEditableRow%20and) for IRow and IEditableRow

**Comment by vinaykulkarni89** [comment]
Dear @VictorTomaili  Thanks for the response, I have already checked the changelog for the BRAKING CHNAGE section - however pretty unclear what action needs to be taken on Rows, if you could give an illustration will be helpful. As IRow is already implemented on the row where I am getting the mentioned error.

"[BREAKING CHANGE] Some row properties are only available via IRow or IEditableRow interface. Introduced IEditableRow and instead of making desktop UI editing (e.g. WPF INotifyPropertyChanged, IsAnyFieldChanged, IsEditing) etc. related properties / methods of row instances only accessible via this interface. They were confusing and polluting the row interface in web applications where they were almost never used. Cast the row instance like ((IEditableRow)row).BeginEdit() etc to access them if ever used. Similary, "IdField, IgnoreConstraints, NameField, Table, TrackAssignments, TrackWithChecks, GetDictionaryData, GetDictionaryDataKeys, SetDictionaryData" properties and fields can only be accessed via IRow interface. This is done to avoid polluting intellisense list as they are very rarely used, and as a preparation to fix swagger / apiexplorer integration"

**Comment by VictorTomaili** [comment]
One of your rows (or rows which you use them to join) may not inherit from the base Row.cs class. This property in the error message exists in the interface, and it is not possible of a missing implementation without a build error. You need to use the Row class instead `IRow` interface. But to use this field in your code, you need to use `((IRow)MyRow).TrackAssignments`

**Comment by vinaykulkarni89** [comment]
Ohh, thanks for the details, will check with this
