### ISSUE TITLE
Inconsistent use of text settings for ApplyChangesButton vs other Buttons

### ISSUE THREAD

**Issue by DGoertzen** [serenity-is/Serenity#6746]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

When App_Data\texts\user.texts.invariant.json is configured to:
```
  "Controls.EntityDialog.ApplyChangesButton": "Save",
  "Controls.EntityDialog.SaveButton": "Save and Close"
```
the title of the SaveButton is set, but it is the hint of the ApplyChangesButton that gets set.

### What did you expect to happen?

I expected that setting the same type of parameter for a button will have the same effect on all buttons.

### How to reproduce?

This can be reproduced by setting App_Data\texts\user.texts.invariant.json to:
```
  "Controls.EntityDialog.ApplyChangesButton": "Save",
  "Controls.EntityDialog.SaveButton": "Save and Close"
```

This problem arises from the code in the lines:
https://github.com/serenity-is/Serenity/blob/4dea5d46752abe74aca6dd84385072f6dbe7f586/src/Serenity.Scripts/corelib/src/ui/dialogs/entitydialog.ts#L904
and 
https://github.com/serenity-is/Serenity/blob/4dea5d46752abe74aca6dd84385072f6dbe7f586/src/Serenity.Scripts/corelib/src/ui/dialogs/entitydialog.ts#L919

I think it would be better to have the buttons behave in the same way, and add local string support for both the title and the hint for all buttons.

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

Serenity Scripts 6.7.0

### Serene template version

6.7.0

### Sergen version

6.7.0

**Comment by volkanceylan** [comment]
works as designed
