### ISSUE TITLE
[Bug report]: RTL Theme not Work with Farisi

### ISSUE THREAD

**Issue by hamadaDev** [serenity-is/Serenity#6820]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

when change Language to  Faris the theme not change to RTL 
so  need help  or update to make it work  again 
thank's
![image](https://github.com/serenity-is/Serenity/assets/11373077/55e13cb4-9a8c-4c43-8755-76c2e77166b0)

### What did you expect to happen?

when change language to Faris/Arabic the theme change to RTL 

### How to reproduce?

try change language to Farsi

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

Last Update 6.7.1.0

### Sergen version

6.7.1.0

### Code editor

vs 2022

### Operating System

windows 10

### Node.js version

16.18.1

### On which device do you see the problem?

DeskTop

**Comment by VictorTomaili** [comment]
There is no RTL CSS in serene. You can implement any BS5 supported RTL CSS.
