### ISSUE TITLE
[Bug report]: grids are not using full height after upgrading to 6.8

### ISSUE THREAD

**Issue by RaptorTrap** [serenity-is/Serenity#6938]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

After upgrading a vanilla serene template to 6.8, all grids are not using the full height and appear squashed:
![image](https://github.com/serenity-is/Serenity/assets/49608875/256809ff-e79d-4c99-846f-91ec1ad93177)

### What did you expect to happen?

Grids using the full height like before.

### How to reproduce?

Create a serene template (6.7.1) upgrade to 6.8 and open any grid

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

6.8

**Comment by VictorTomaili** [comment]
Use CSS to make it full height. Check the [changelog](https://github.com/serenity-is/Serenity/blob/master/CHANGELOG.md).

**Comment by RaptorTrap** [comment]
I know that I can change it through css, but shouldn't it work out of the box, if it was working fine the version before?

**Comment by volkanceylan** [comment]
See this commit https://github.com/serenity-is/serene/commit/348802081e1ae72ca5f2b988d0c276a08bfbfe00

This is not a Serenity issue, and it is clearly stated in changelog that changes should be applied manually after updating
