### ISSUE TITLE
Opening the edit URL in a new browser tab first loads the listing page and then subsequently loads the entity.

### ISSUE THREAD

**Issue by EdwinThomas11** [serenity-is/Serenity#6969]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

I'm looking to open an edit dialog in a new browser tab from the listing page. Currently, I can achieve this using window.open(), but it loads the listing page first and then subsequently loads the entity dialog. I'm seeking assistance to bypass the listing page and load the entity dialog directly in a new browser tab.

### What did you expect to happen?

It should not open the listing page on new browser tab.

### How to reproduce?

Paste the edit URL and paste it in the new browser tab.

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

3.12.6

**Comment by EdwinThomas11** [comment]
I'm looking to open an edit dialog in a new browser tab from the listing page. Currently, I can achieve this using window.open(), but it loads the listing page first and then subsequently loads the entity dialog. I'm seeking assistance to bypass the listing page and load the entity dialog directly in a new browser tab. Your help with this would be greatly appreciated.

**Comment by VictorTomaili** [comment]
Use discussions.

**Comment by EdwinThomas11** [comment]
https://github.com/orgs/serenity-is/discussions/6968
