### ISSUE TITLE
Automatically displaying the editor popup within a panel when the 'Yes' option is selected in a confirmation popup.

### ISSUE THREAD

**Issue by EdwinThomas11** [serenity-is/Serenity#6977]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

When an entity is opened within a panel and a confirmation popup appears before saving, clicking 'Yes' not only saves the entity but also triggers the opening of an editor popup simultaneously.

### What did you expect to happen?

It should not open an editor popup in the panel

### How to reproduce?

When an entity is opened within a panel and a confirmation popup appears before saving, clicking 'Yes' not only saves the entity but also triggers the opening of an editor popup simultaneously.

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

3.12.6

**Comment by EdwinThomas11** [comment]
I've noticed that this generally occurs when the URL is changed. @VictorTomaili appreciate your inputs here.

**Comment by EdwinThomas11** [comment]
I've observed that when the URL is in the format "~/Default/Entity#", if I modify the browser's URL manually to "~/Default/Entity#edit123," the popup appears. @VictorTomaili appreciate your inputs here at the earliest.

**Comment by VictorTomaili** [comment]
The problem you are facing is not related to the framework, but to your own code. The serenity 3.x versions are no longer supported. You can prefer to upgrade your project to 6.x. Please continue on discussions.
