### ISSUE TITLE
[Bug report]: BasedOnRowPropertyNameAnalyzer inherited fields

### ISSUE THREAD

**Issue by marcobisio** [serenity-is/Serenity#7006]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

Inherited fields aren't recognised by new BasedOnRowPropertyNameAnalyzer feature (both in form and columns):

![image](https://github.com/serenity-is/Serenity/assets/17425690/aa07ad06-1539-421e-a258-4ba2d832ef11)

They belong to the abstract class LoggingRow (similar to https://github.com/serenity-is/common-features/blob/d035f35686ffa79701ee2af73d4fda69a2f47a89/src/Serenity.Extensions/Modules/BaseEntities/LoggingRow.cs#L10) which is implemented by the xyzRow of the image above.
Adding IgnoreName attribute is the only workaround that I found right now.

### What did you expect to happen?

Form and Columns should recognise also inherited fields.

### How to reproduce?

Just create an entity which inherit from LoggingRow and try to add one of the inherited fields to the Form or to the Columns.

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

6.9.5

**Comment by volkanceylan** [comment]
Thanks @marcobisio, fixed and will be released with next version

**Comment by marcobisio** [comment]
Thanks @volkanceylan !
