### ISSUE TITLE
HtmlContentEditor is not working when opened in Panel

### ISSUE THREAD

**Issue by EdwinThomas11** [serenity-is/Serenity#7007]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

I tried to utilize the HtmlContentEditor within the form. It functions properly when the form is displayed as a dialog, but it doesn't work when the form is displayed as a panel.

### What did you expect to happen?

It should work within the panel too.

### How to reproduce?

Add HtmlContentEditor for a string property and open the form in a panel.

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

Serenity.Scripts 3.12.6

**Comment by volkanceylan** [comment]
Use discussions. Users are not allowed to assign issues.
