### ISSUE TITLE
.NET 8 Migration

### ISSUE THREAD

**Issue by volkanceylan** [serenity-is/Serenity#7020]
This update is a significant release tailored for .NET 8. Before migrating to this version (8.0+), ensure that your Visual Studio 2022 version is 17.8.0 or later. If not using Visual Studio, manually install .NET SDK 8 to proceed.

#### Configuration Changes

1. Update your project file to target `.NET 8.0` by modifying the following line:
    ```xml
    <TargetFramework>net8.0</TargetFramework>
    ```

2. Update the packages listed below to at least the specified versions:
    ```xml
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.2" />
    ```

3. Additionally, update references to Serenity and any Pro packages to version 8.0.0 or later. These changes should facilitate a smooth transition to .NET 8, as there aren't many breaking changes affecting Serenity-based applications.

Please note that Serenity 8.0+ packages will no longer provide support for .NET 6/.NET 7. Ensure compatibility by making necessary updates to align with .NET 8.

#### Serene Transition to .NET 8

Although a .NET 8 version of Serene won't be released immediately, this decision is to avoid potential issues for users who might not have updated their Visual Studio to version 17.8.0. Serene users can manually implement the changes outlined in these release notes once they have updated their Visual Studio and are ready to switch to .NET 8.

This approach aims to prevent issues for newcomers downloading Serene without the required Visual Studio update.

**Comment by Surenthiran** [comment]
after updating dotnet sergen restore gives following error 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Serenity.CodeGenerator.RestoreCommand.Run(String csproj, Boolean verbose) in C:\Sandbox\startsharp\Serenity\src\Serenity.Net.CodeGenerator\Commands\RestoreCommand.cs:line 317
   at Serenity.CodeGenerator.Program.Run(String[] args, IGeneratorFileSystem fileSystem, Func`1 projectSystemFactory) in C:\Sandbox\startsharp\Serenity\src\Serenity.Net.CodeGenerator\Program.cs:line 8

**Comment by Surenthiran** [comment]
After updating to 8 getting tons of type script error 

![image](https://github.com/serenity-is/Serenity/assets/2942248/9cde4116-16ae-48fa-a5bc-6fb302fe7522)

am not sure what i did wrong

**Comment by VictorTomaili** [comment]
Please use discussions for questions and support.

**Comment by volkanceylan** [comment]
Update: Serene 8.4.7.0 with .NET8 support is released on 2024-04-28
