### ISSUE TITLE
Column resizing not working in Firefox

### ISSUE THREAD

**Issue by edwardch** [serenity-is/Serenity#7089]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

- When trying to resize a column in a grid using Firefox, the column does not get resized
- Trying to do it in MS Edge works as expected
- I get the same result on the Serenity demo and in local dev environment
- Same result on another person's PC

### What did you expect to happen?

User should be able to resize columns in a grid using any modern browser.

### How to reproduce?

1. Open Firefox
2. Navigate to https://demo.serenity.is/Northwind/Order
3. Try to resize any column in the grid

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

8.3.3,8.3.4

### Code editor

Visual Studio 2022

### Operating System

Windows 11

### Node.js version

v18.18.0

### Database type and version

SQL Server

### On which device do you see the problem?

Desktop

### On which operating system do you see the problem?

Windows (11)

### On which browsers do you see the problem?

Firefox

### On what version of the browsers do you see the problem?

123.0

**Comment by volkanceylan** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=505521

Issue was due to this bug in Firefox. Should be fixed in next version.

**Comment by edwardch** [comment]
Thanks for finding (and fixing) this, Volkan. Looks like a 15 year old bug!

The column resizing in FF worked in the previous version of Serenity, though I know you've been doing lots of work across all areas so this might've snuck in.

Thanks again for all the work, and for getting onto this so quickly.

Cheers!
Edward

**Comment by volkanceylan** [comment]
It worked in previous versions because we were using jquery.event.drag / jquery.resizable etc. which probably had workarounds for this issue.
