### ISSUE TITLE
[Bug report]: Grid custom filter not working with text input

### ISSUE THREAD

**Issue by edwardch** [serenity-is/Serenity#7117]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

The custom grid filters ("edit filter" link on bottom right of grid) is not working. You can type in custom text for contains/equals on a field, and when you click OK, the filter does not get added, and the grid does nothing.
If you add only one filter on a field that are from a dropdown list, it works. (like Category in the Products page).

### What did you expect to happen?

The field filter with custom entered text should be added to the filters when clicking OK.

### How to reproduce?

- Navigate to https://demo.serenity.is/Northwind/Product#
- Click "edit filter" 
- Select Product Name
- Type in "ch"
- Click OK
- No filter gets applied

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

8.4.1

### Operating System

Windows 11

### Node.js version

v18.18.0

### Database type and version

SQL Server

### On which device do you see the problem?

Deskop

### On which operating system do you see the problem?

Windows (11)

### On which browsers do you see the problem?

Firefox, Microsoft Edge

### On what version of the browsers do you see the problem?

Latest

**Comment by volkanceylan** [comment]
Thanks @edwardch, should be fixed in 8.4.5
