### ISSUE TITLE
[Bug report]: Can't get current UserId on version 8.4.4

### ISSUE THREAD

**Issue by s10730047** [serenity-is/Serenity#7123]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

I just need to get Authorization.UserID in SomeDialog.ts

I was try 
`const userId =  Authorization.userDefinition.UserId`
and
`const userId = Authorization.UserId`

But it's not found UserId in Authorization and Authorization.userDefinition

### What did you expect to happen?

Success in getting the current  UserID

### How to reproduce?

Use Serenity 8.4.4

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

Serenity 8.4.4

### Node.js version

v20.12.2

**Comment by VictorTomaili** [comment]
Please use discussions
