### ISSUE TITLE
Improve TabsExtensions

### ISSUE THREAD

**Issue by volkanceylan** [serenity-is/Serenity#7130]
- Make it possible to toggle/disable tabs either by key / index
- Allow getting tab index/key from an editor in the tab etc.
- Set data-tabkey based on the default tab title (remove accents?)
- Maybe introduce a Tabs class similar to Dialog class for working with tabs of different types (bs, ui etc.)

**Comment by LSNicholls** [comment]
I would like to applaud and upvote this!  :-)

We had a method for setting focus to a different tab in a dialog on open, depending on the status of the contents, that worked in 6.x but no longer works in 8.  I can see that the structure of the generated tabset is pretty different now.  I have been able to figure out a new method of disabling or toggling the tab contents and the relevant, separate list element in the property tab set.  But I haven't been able to figure out how to set the focus to a specific tab the way we did before.  It sounds like this would solve the problem!
