### ISSUE TITLE
An unhandled exception occurred while processing the request. InvalidOperationException: Generated PDF file is empty![Bug report]: <Short description of the bug>

### ISSUE THREAD

**Issue by AMRAAMMU** [serenity-is/Serenity#7170]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

An unhandled exception occurred while processing the request.
InvalidOperationException: Generated PDF file is empty!
Serenity.Reporting.HtmlToPdfConverter.Execute()

Stack Query Cookies Headers
InvalidOperationException: Generated PDF file is empty!
Serenity.Reporting.HtmlToPdfConverter.Execute()
BitPro.SchoolMate.ReportController.RenderAsPdf(IReport report, string key, string opt) in ReportController.cs
BitPro.SchoolMate.ReportController.Execute(string key, string opt, string ext, bool download, bool printing) in ReportController.cs
lambda_method(Closure , object , object[] )
Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(object target, object[] parameters)
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Show raw exception details
the others are working properly and in the local db also working this report correctly but in live is showing the error

### What did you expect to happen?

want to solve this error as soon as possible

### How to reproduce?

i dont now

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

Serenity.Scripts.3.9.14

### Operating System

Windows 11

**Comment by VictorTomaili** [comment]
Please use discussions

**Comment by AMRAAMMU** [comment]
How

**Comment by VictorTomaili** [comment]
https://github.com/serenity-is/Serenity/discussions
