### ISSUE TITLE
[Bug report]: Incorrect validation message for password change

### ISSUE THREAD

**Issue by edwardch** [serenity-is/Serenity#7229]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

On the demo site, when changing a password, I enter `SERENITY1` and the validation rule fails saying that a digit is required, even though there is a digit in the password. 

It appears that the lower character error message is showing the digit message

https://github.com/serenity-is/common-features/blob/0354b790db9a45d80c2ad104a275458828ec7179/src/Serenity.Extensions/Modules/Membership/PasswordStrength/PasswordStrengthValidation.ts#L25

### What did you expect to happen?

Show the lower character error if there is no lower character in the password and the password requires it.

### How to reproduce?

- via Forgot password email link
- on the Account/ChangePassword page

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

8.6.x (Latest Demo)

### Serene template version

8.6.2

### Code editor

Visual Studio 2022

### Operating System

Windows 11

### On which device do you see the problem?

Desktop

### On which operating system do you see the problem?

Windows (11)

### On which browsers do you see the problem?

Firefox, Microsoft Edge

### On what version of the browsers do you see the problem?

Latest

### Additional information

It would be useful to show the password requirements to the user based on what the configuration is.
e.g

Password requires:
- at least one UPPERCASE character
- at leat one lowercase character
- at least one number from 0-9
- at least one non alphanumeric character (e.g %$!/&)

what do you think?

**Comment by volkanceylan** [comment]
Should be fixed in 8.6.3
