### ISSUE TITLE
[Bug report]: Lookupeditor sorting selected items A-Z, falsley triggering pendingChangesConfirmation

### ISSUE THREAD

**Issue by shakazulu89** [serenity-is/Serenity#7253]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

As title suggest, saved items of a lookupeditor field get automatically alphabetized. this is causing the savestate to be different from the loadedstate as the order of these items are different from what is returns in the item retrieve service. This causes the pending changes confirmation dialog to appear even though no changes are made.

### What did you expect to happen?

I expect the items stay in the same order they were added. or at the very least have pending changes confirmation login understand items have not changed, only their order.

### How to reproduce?

Go into northiwind customer dialog, add representatives but make sure to first add a name that starts with a letter after 'A', for example "Roger King" and then add "Andrew Fuller". Then save. 

Then open the same customer dialog and notice the names have switched, Andrew is first then Roger. Then, without doing anything, simply try to close the dialog. 
You will be prompted to save changes even though no changes have been made.

Furthermore, even if you do save the dialog now, and then go back in to the dialog, and then again try to exit without saving, you will still be prompted to save...

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

8.5.6

### Serene template version

8.5.6

### Additional information

This is also happening on startsharp live demo site...

**Comment by VictorTomaili** [comment]
Cannot reproduced in demo. https://demo.serenity.is/Northwind/Customer#edit/1

**Comment by shakazulu89** [comment]
Strange .. i just did it there again... hold on ill make a clip

**Comment by shakazulu89** [comment]
https://github.com/user-attachments/assets/c0329efc-cf2c-49a0-9224-a0b85ac887ca



this time though when i saved and went back in again it didnt ask me again to save changes.. weird

**Comment by VictorTomaili** [comment]
When you press save and close, yes it saves the data without order the values and it causes this prompt.   When using only the save button, there is no issue. We will look into it.

**Comment by volkanceylan** [comment]
This should be solved in 8.7.1
