### ISSUE TITLE
[Bug report]: NotesEditor CSS not loading

### ISSUE THREAD

**Issue by shakazulu89** [serenity-is/Serenity#7266]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

Look at notes editor even in the demo site. add a note, it has no style.

![image](https://github.com/user-attachments/assets/b9aa4987-acaa-4ae5-8065-be6751222076)

### What did you expect to happen?

that the notes have a box around them, etc.

### How to reproduce?

go to customer dialog and add a note.

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

8.7

### Serene template version

8.7

### Additional information

as a side note, the customer, product and order grids are not working on the demo site...

**Comment by VictorTomaili** [comment]
fixed

**Comment by VictorTomaili** [comment]
https://github.com/serenity-is/common-features/blob/e51cdd7ceeda8becfda9e1855b39ee6de170340b/src/Serenity.Demo.Northwind/Modules/Note/NotesEditor.css

https://github.com/serenity-is/common-features/blob/e51cdd7ceeda8becfda9e1855b39ee6de170340b/src/Serenity.Demo.Northwind/Modules/Note/NotesEditor.tsx#L5C1-L6C1

**Comment by shakazulu89** [comment]
I dont know if this is related but when i click to edit a note the textEditor is null:

### NoteDialog.tsx

```
set text(value: string) {
this.textEditor.value = value;
}
```

**Comment by shakazulu89** [comment]
scaratch that .. for some reason i had this queueMicrostask method in the rendercontents method of notedialog .. no idea how that got there?

 
```
<form id={id.Form} class="s-Form" >
    <textarea id={id.Text} class="required" ref={el => queueMicrotask(() =>
        this.textEditor = new HtmlNoteContentEditor({ element: el }))} />
</form>
```
