### ISSUE TITLE
[Bug report]: The new serenity extension with version components is not working  8.7.1 - visual studio 2022 

### ISSUE THREAD

**Issue by sz-dev** [serenity-is/Serenity#7271]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

[Bug report]: The new serenity extension with version components is not working  8.7.1 - visual studio 2022 
Trying to create a sample project with northwind

Created a solution and getting below error on build 
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	NU1102	Unable to find package Serenity.Extensions with version (>= 8.7.1.1)
  - Found 126 version(s) in nuget.org [ Nearest version: 8.7.1 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in C:\Program Files\dotnet\library-packs	Serene6_8.6.4North.Web	C:\Users\abc\source\repos\Serene6_8.6.4North\Serene6_8.6.4North\Serene6_8.6.4North.Web\Serene6_8.6.4North.Web.csproj	1		

### What did you expect to happen?

the project should be created without any issue like it used to with version 8.6.4

### How to reproduce?

[Bug report]: The new serenity extension with version components is not working  8.7.1 - visual studio 2022 
Trying to create a sample project with northwind

Created a solution and getting below error on build 
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	NU1102	Unable to find package Serenity.Extensions with version (>= 8.7.1.1)
  - Found 126 version(s) in nuget.org [ Nearest version: 8.7.1 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in C:\Program Files\dotnet\library-packs	Serene6_8.6.4North.Web	C:\Users\abc\source\repos\Serene6_8.6.4North\Serene6_8.6.4North\Serene6_8.6.4North.Web\Serene6_8.6.4North.Web.csproj	1		

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

8.7.1

### Relevant log output

```console
[Bug report]: The new serenity extension with version components is not working  8.7.1 - visual studio 2022 
Trying to create a sample project with northwind

Created a solution and getting below error on build 
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	NU1102	Unable to find package Serenity.Extensions with version (>= 8.7.1.1)
  - Found 126 version(s) in nuget.org [ Nearest version: 8.7.1 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in C:\Program Files\dotnet\library-packs	Serene6_8.6.4North.Web	C:\Users\abc\source\repos\Serene6_8.6.4North\Serene6_8.6.4North\Serene6_8.6.4North.Web\Serene6_8.6.4North.Web.csproj	1
```

### Serene template version

8.7.1

### Sergen version

8.7.1

### Code editor

visual studio 2022

### Operating System

windows 11

### Node.js version

v 18.14.0

### TypeScript version

1.0.0

### Database type and version

sql 2022

### On which device do you see the problem?

desktop

### On which operating system do you see the problem?

windows

### On which browsers do you see the problem?

Chrome

### On what version of the browsers do you see the problem?

130

### Additional information

8.7.1

**Comment by volkanceylan** [comment]
Please try again.
