### ISSUE TITLE
"Editor class not found" when creating an editor for a Master/Detail relationship

### ISSUE THREAD

**Issue by DGoertzen** [serenity-is/Serenity#7273]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

I followed the instructions for creating a master / detail list according to the instructions at https://serenity.is/docs/tutorials/movies/10-keeping-record-of-the-cast.  _Note that these instructions seem to be somewhat out of date as JQuery is still referenced in the code._

When executing the code, I get the error message "Message: Uncaught Exception: "xxx.xxx.xxx" editor class not found!  Make sure there is such a editor type under the project root namespace.  ...   "side-effect-import" this editor class from the current page.ts/grid.ts/dialog.ts file (import "./path/to/MyEditor.ts").  "  This error is coming from the file https://github.com/serenity-is/Serenity/blob/a2e98657a0849c0584f653f3ba840ec5760c07c3/packages/corelib/src/types/editortyperegistry.ts#L21

The instructions at https://serenity.is/docs/tutorials/movies/10-keeping-record-of-the-cast. don't say anything about this side-effect-import.  I could get my application to work by following the instructions, but it seems to be a very odd way to make it work, as the compiler does not recognize there is an issue.  Also, I didn't have to do this in earlier versions of Serenity.

Can you confirm if:
a) Do you now need to "side-effect-import" editor classes to the "page.ts/grid.ts/dialog.ts file all the time? and should the instructions at https://serenity.is/docs/tutorials/movies/10-keeping-record-of-the-cast . be updated?, or
b) Have I configured something wrong in my environment, and there is a way to avoid using the "side-effect-import"?

Thanks.

### What did you expect to happen?

I expected that by following the instructions at https://serenity.is/docs/tutorials/movies/10-keeping-record-of-the-cast, it would have produced a detail editor that works without further changes.

### How to reproduce?

Follow the example at https://serenity.is/docs/tutorials/movies/10-keeping-record-of-the-cast with Serenity 8.7.1

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

8.7.1

### Code editor

Visual Studio 2022, Version 17.11.4

### On which device do you see the problem?

Desktop

### On which operating system do you see the problem?

Windows

**Comment by VictorTomaili** [comment]
When you use some classes which are not referenced, you may see this error. For this case, you need to use side effect import. Please use discussions to ask any questions. We are working on updating the tutorials.

**Comment by DGoertzen** [comment]
ok.  Thanks!

**Comment by VictorTomaili** [comment]
Check the updated version. You need to add dialog type to your grid editor.
