### ISSUE TITLE
ConnectedMode doesnt work when creating new entity

### ISSUE THREAD

**Issue by shakazulu89** [serenity-is/Serenity#7285]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use [discussions](https://github.com/serenity-is/Serenity/discussions) for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the [Serenity Platform website](https://serenity.is/docs/)
- [X] I have read the [frequently asked questions](https://serenity.is/docs/startsharp/faq)
- [X] I have searched my problem in the [discussions and the old issues](https://github.com/serenity-is/Serenity/discussions)

### What happened?

Take a look at live demo. If you create a new order, then try to add a new order detail, that detail is not being saved. it only works if you first save the order, and then add a detail. 

### What did you expect to happen?

expected to be able to add a detail without having to first save the order.

### How to reproduce?

Take a look at live demo. If you create a new order, then try to add a new order detail, that detail is not being saved. it only works if you first save the order, and then add a detail. 

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

8.7.6

**Comment by volkanceylan** [comment]
Connected mode only works for edit mode, how can we save without and OrderID

**Comment by shakazulu89** [comment]
i understand but you agree that this is not a good user experience .. that if he creates a new order and adds a detail this detail doesnt get saved. he has to first save the order and only then can add a detail. i thought this piece of code is supposed to cover that but it doesnt seem to be working:

```
protected override async validateEntity(row: OrderDetailRow, id: any) {
        row.ProductID = toId(row.ProductID);

        var sameProduct = this.view.getItems().find(x => x.ProductID === row.ProductID);
        if (sameProduct && this.itemId(sameProduct) !== id) {
            alertDialog('This product is already in order details!');
            return false;
        }

        if (this.connectedMode)
            return true;

///////////// ****************** this should populate the order detail if no order id yet, right? ************* //////////////////

        const lookup = await ProductRow.getLookupAsync();
        row.ProductName = lookup.itemById[row.ProductID].ProductName;
        row.LineTotal = (row.Quantity || 0) * (row.UnitPrice || 0) - (row.Discount || 0);
        return true;
    }
```

**Comment by volkanceylan** [comment]
The code you show populates calculated / foreign fields for in-memory mode, and is not required for connected mode, thus the shortcut above. It has nothing to do with this bug btw, the grid editor pushes the item to the items array if this method returns true, but the view's setItems method is not called unlike it was before, so the view/grid is not aware something changed.

**Comment by shakazulu89** [comment]
ok phew .. glad i didnt say something too silly :P
