### ISSUE TITLE
[Bug report]: Issues with Installation/setup in Linux

### ISSUE THREAD

**Issue by LSNicholls** [serenity-is/Serenity#7289]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use [discussions](https://github.com/serenity-is/Serenity/discussions) for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the [Serenity Platform website](https://serenity.is/docs/)
- [X] I have read the [frequently asked questions](https://serenity.is/docs/startsharp/faq)
- [X] I have searched my problem in the [discussions and the old issues](https://github.com/serenity-is/Serenity/discussions)

### What happened?

There are various small problems with following "Getting Started" steps on a recent Linux build (Linux Mint 21.3). using Serene.Templates::8.7.4, npm 10.9.0, node v23.3.0.  

When the small problems are resolved and the project builds and runs without error, nothing shows on the login page.  I'm pretty sure this is related to esbuild somehow, but don't know what to do to resolve it.

1. Since MS local db is not available, I made the requisite changes to work with MySQL.  I also gave wide permissions to the full .Web folder and files, since this is a test application.  At this point, I could build and run, with some problems.  I made no other changes to the generated Template code.

1. I saw a lot of MySQL errors during the migration, although the tables in both Default and Northwind schemas were created and filled out, in the main.  This was not my main concern, so I installed SQL Server for Linux and continued, but I remember seeing [an issue](https://github.com/serenity-premium/startsharp/issues/1030) that indicated recent MySQL problems that "should be resolved in 8.7.1", so I'm telling you that they aren't all gone, apparently.  If you want details, please let me know and I'll do a new test and capture everything.

2.  Once I switched to SQL Server for Linux, I found difficulties with the migration because the SQL identity couldn't create the databases properly.  This is because it was trying to create them in App_Data rather than the default location for new databases; is there a way to fix this in the migration scripting, so that the right location is used?  I resolved this by creating the databases myself, and rerunning the app; the MS SQL version of migrations ran perfectly in existing databases.

3. During `dotnet build` execution I received this warning on first `dotnet build`:
`/home/linich/Documents/AspNetCore/Test2/Test2.Web/Test2.Web.csproj(55,5): warning MSB3073: The command "dotnet sergen servertypings -p "Test2.Web.csproj" -prop:Configuration=Debug -prop:AssemblyName="Test2.Web" -prop:ESMAssetBasePath="" -prop:OutDir="bin\Debug/net8.0/" -prop:RootNamespace=Test2 -prop:TargetFramework=net8.0" exited with code 12.
`
... the problem is in the OutDir,` "bin\Debug/net8.0/"` - the first backslash needs to be a forward slash.   I am  not sure how to fix this in the scripting, but was able to re-run the command with the proper argument, and no warnings or errors.

4. Now `dotnet run` works, and the application redirects me to the login page, which appears to be empty.  Source shows an empty LoginPanel div, along with the other normal Serenity contents.    The browser console shows this error:  `Loading failed for the <script> with source “http://localhost:5000/Serenity.Corelib/index.global.js?v=2024112711”. Login:41:89`

I tried using a different browser and clearing cookies no difference. I also tried switching back to MySQL and saw exactly the same.

I re-checked the permissions of Serenity.CoreLib.dll, and everybody has all rights to it, so I don't know what's missing there.

I remembered [something similar](https://github.com/serenity-premium/startsharp/issues/987) where I got the contents of the page back by un-mininifying and not bundling, but that made no difference in this case.  Neither did adding `services.AddEsBuildMinifiers()`.  

5. At this point I wanted to check the esbuild version, and the OS reported that esbuild was not installed (?).  So this might be another item for your "Getting started" list, or is it built into dotnet sdk?  I'm sorry that I have no clue how this works. When I explicitly  installed it, it said the version was 0.14.11.   Is this okay?  It made no difference.

### What did you expect to happen?

I expected to see a login screen.

### How to reproduce?

I'm pretty sure you can see this in whatever recent version of Linux you want.   And you can see this with MySQL, you don't need to use SQL Server. If you want to repro the SQL Server part, note that you'll have to do some extra work to get it to install and run, or drop down to a supported Linux build.  

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

Serenity.Scripts 8.1.2

### Relevant log output

```console
There is nothing relevant in the log. The last executed statement is the SELECT from the Languages table, and the only startup warning is the expected failure to determine https port for redirect.
```

### Serene template version

8.7.4

### Sergen version

8.7.4.0

### Code editor

Just a text editor, I didn't really edit anything

### Operating System

Linux Mint 21.3

### Database type and version

MySQL 8.0.40 and Microsoft SQL Server 2022 (RTM-CU16) (KB5048033) - 16.0.4165.4 (X64)  	Nov  6 2024 19:24:49  	Copyright (C) 2022 Microsoft Corporation 	Express Edition (64-bit) on Linux (Linux Mint 21.3) <X64>

### On which operating system do you see the problem?

Linux

### On what version of the browsers do you see the problem?

Same behavior in Firefox and Chrome

**Comment by volkanceylan** [comment]
In linux you should setup your database yourself, and set connection strings and providername. Our demo runs on linux, github actions runs on linux. There is no way to modify connection strings with dotnet new. The migrations should run, we tested them in linux with docker and all db types previously. Mysql not having write access to your appdata etc is out of scope.

**Comment by LSNicholls** [comment]
@volkanceylan, thank you, I re-created with a fresh sample to see the migration errors and this time, with the database created first in MySQL, the migration did go without error.  

Please note:  on the first sample, it seemed like MySQL created the databases fine by itself, it was SQL Server that tried to create them in App_Data, not MySQL.  But MySQL migration then failed on some minor things like the ones that you indicated should be solved in 8.7.1.  With the databases pre-created, there were no problems at all.

Respectfully, I do think the Getting Started instructions should indicate that the databases should be created manually before migrations run in Linux, maybe for all database engines.

**Please address these issues, which are not related to the databases**:

1. The scripting change I am suggesting is for the dotnet sergen command that runs during build. On `dotnet build`, I got a warning because the sergen command couldn't run properly: `The command "dotnet sergen servertypings -p "Test2.Web.csproj" -prop:Configuration=Debug -prop:AssemblyName="Test2.Web" -prop:ESMAssetBasePath="" -prop:OutDir="bin\Debug/net8.0/" -prop:RootNamespace=Test2 -prop:TargetFramework=net8.0"
`, which I resolved by re-running the command manually with a fix to the prop:OutDir argument, as stated (fixing initial backslash to forwardslash).  I don't *think* this is related to the blank login page?
2. On `npm -i` I get this warning:  `(node:18820) ExperimentalWarning: CommonJS module [ ..] node.js is loading ES Module [..] node_modules/supports-color/index.js using require(). Support for loading ES Module in require() is an experimental feature and might change at any time`.  Does this help explain why my login screen is blank?
3. On `npm -i` , I also get a warning about high vulnerability for cross-spawn, which I resolved with npm audit fix.  Should I not have done that?
4. When I run `dotnet build`, it seems to run fine and without error (after the manual dotnet sergen command described above).  BUT if I run `sudo dotnet build` I DO see 2 errors, both of which say the same thing: 
``` 
Executing TypeScript compiler for Test2.Web...

 file:///home/linich/Documents/AspNetCore/Test2/Test2.Web/tsbuild.js:5
  await build({
  ^^^^^
    SyntaxError: Unexpected reserved word
      at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
      at async link (internal/modules/esm/module_job.js:42:21)
/home/linich/Documents/AspNetCore/Test2/Test2.Web/Test2.Web.csproj(60,5): warning MSB3073: The command "node ./tsbuild.js" exited with code 1. 
``` 
Does this explain what is going on with the blank login page ?   Do I need to update TypeScript? Package.json and package-lock.json have ^5.7.2.  

Additional notes:

* I commented out StartNodeScripts line per [this issue](https://github.com/orgs/serenity-is/discussions/7030); it didn't make any difference to this problem.
* FWIW, I have given full permissions to everybody for all the files and folders in this application, so it is not involved in the issues I am seeing.


Thank you.

**Comment by volkanceylan** [comment]
You are probably using an old node version in that machine, check node -v npm -v and compare with lts versions. Linux dists dont have an up to date node. That forward slash issue is not a problem, latest sergen replaces them, is your sergen tool old?

**Comment by LSNicholls** [comment]
As I said in the first line of my first message, sergen is definitely 8.7.4.0, is there a later version?  I saw the problem with the backslash on each attempt.  Since this is a fresh VM, there is really no way that sergen could have been an earlier version at any point.

I do see that all the other slashes were replaced, just not the first one.

OTOH... I thought, and wrote earlier, that I was using node v23.3.0 .  But clearly there are different versions on the machine, which explains the difference between using sudo and not:
![image](https://github.com/user-attachments/assets/ac58382c-6904-4d3c-babd-6be6df655697)

This explains why I get different behavior when trying to use sudo for a build/run, but not why I get the blank login screen either way.

I think I am going to give up on this.  Sorry for the trouble, @volkanceylan.

**Comment by volkanceylan** [comment]
Sudo one is probably showing the version installed for root user or the global one, while yours is installed in user mode with linich. User mode installation of node/npm should be avoided.

Anyway, your problem might be related to https://github.com/serenity-is/Serenity/issues/7290, e.g. the invalid casing for Serenity.Corelib (it was published to Nuget as Serenity.CoreLib, notice casing since 8.7.3).
 You may try again with 8.8.1.0 or update Serenity libs to 8.8.1

**Comment by volkanceylan** [comment]
For node installation, I recommend node source (though I am no Linux expert fyi):
// https://github.com/nodesource/distributions?tab=readme-ov-file#ubuntu-versions
curl -fsSL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt-get install -y nodejs
sudo npm i -g npm@latest
