### ISSUE TITLE
[Bug report]: EditLink to open another dialog (also failes on Serenity.is demo page)

### ISSUE THREAD

**Issue by Gulgil1** [serenity-is/Serenity#7295]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use [discussions](https://github.com/serenity-is/Serenity/discussions) for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the [Serenity Platform website](https://serenity.is/docs/)
- [X] I have read the [frequently asked questions](https://serenity.is/docs/startsharp/faq)
- [X] I have searched my problem in the [discussions and the old issues](https://github.com/serenity-is/Serenity/discussions)

### What happened?

I can't get [EditLink] to work with opening another dialog.

I have this in my XYZColumns.cs
```
    [DisplayName("External Domain Partner Id")]
    public Guid ExternalDomainPartnerId { get; set; }

    [DisplayName("Partner")]
    [EditLink(IdField = "ExternalDomainPartnerId", ItemType = "ExternalDomain.Partner")]
    public string ExternalDomainPartnerName { get; set; }
```
And PartnerDialog
```
@Decorators.registerClass("CompanyNS.ExternalDomain.PartnerDialog")
export class PartnerDialog extends FelineEntityDialog<PartnerRow, any> {
  protected form = new PartnerForm(this.idPrefix);
```

When I  click the link, it just says it can't find the dialog.

On the Serenity.is demo page I get the same error on Territory page (try clicking on a region link):
https://demo.serenity.is/Northwind/Territory

"Demo.Northwind.Region" dialog class not found! Make sure there is such a dialog type under the project root namespace

Is it a general error, or what am I suppose to put in ItemType of EditLink to make it open?
I have also tried (none work):
[EditLink(IdField = "ExternalDomainPartnerId", ItemType = "ExternalDomain.Partner")]
[EditLink(IdField = "ExternalDomainPartnerId", ItemType = "CompanyNS.ExternalDomain.Partner")]
[EditLink(IdField = "ExternalDomainPartnerId", ItemType = "CompanyNS.ExternalDomain.PartnerDialog")]

### What did you expect to happen?

I expect it to open the correct dialog

### How to reproduce?

Just go to https://demo.serenity.is/Northwind/Territory and click a region link.

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

8.6.3

**Comment by volkanceylan** [comment]
Side effect import the dialog class to your grid.ts
